### ISSUE TITLE
a React component.

### ISSUE THREAD

**Issue by hustcc** [frappe/gantt#10]
[gantt-for-react](https://github.com/hustcc/gantt-for-react) is Frappe Gantt components for React wrapper.

Now is v0.0.1, just can use it in react, but need to upgrade, supports are needed.

I need to update the gantt when tasks updated, so I need an api 

```js
gantt.update_tasks(tasks);
```

to change the gantt dynamically. The api is similar with 

```js
gantt.change_view_mode('Week')
```

Can you do this to help ?

**Comment by netchampfaris** [comment]
Just pushed https://github.com/frappe/gantt/commit/ac374003906994340e8583e1a6af5d48947e99ec

**Comment by hustcc** [comment]
Thanks, let me do a test.

**Comment by hustcc** [comment]
In addition, the 1st parameter should  be compatible with selector string and dom object:
```js
var gantt = new Gantt("#gantt", tasks);
// or
var gantt = new Gantt(document.getElementById('#gantt'), tasks);
```

then in react, I can use

```js
var gantt = new Gantt(this.refs.ganttdom, tasks);
```

so, there will be no need to generate a unique id for react component dom.

**Comment by hustcc** [comment]
error here:

![image](https://cloud.githubusercontent.com/assets/7856674/22957480/73bc280e-f363-11e6-96f8-3d6b7fc8d5a4.png)

![image](https://cloud.githubusercontent.com/assets/7856674/22957491/800d1a0a-f363-11e6-8d6a-2148e99799b5.png)
