### ISSUE TITLE
Different display on weekends

### ISSUE THREAD

**Issue by fbatiga** [frappe/gantt#102]
Hello,

Is is possible to style the weekends differently ? 

Currently it is difficult to plan tasks without resorting to a calendar to know when are the weekends.

**Comment by enyosolutions** [comment]
@netchampfaris Do you know i could go about modifying the library to do this ?

**Comment by netchampfaris** [comment]
This is the part which highlights today's date: https://github.com/frappe/gantt/blob/master/src/index.js#L392

Maybe we could have a generic highlighter that can work on any date.

**Comment by jeffberube** [comment]
For what it's worth, I create a class called 'weekend-highlight' that I added to the .css sheet and modified the make_grid_highlights function like so:

```
    make_grid_highlights() {

	if (this.view_is('Day')) {

		const width = this.options.column_width;
		const height =
			(this.options.bar_height + this.options.padding) *
				this.tasks.length +
				this.options.header_height +
				this.options.padding / 2;

		let x = 0;

		for (let date of this.dates) {
							
			let y = this.options.header_height + this.options.padding / 2;

			let isToday = date.toString() == date_utils.today();
			let isWeekend = (date.getDay() == 0 || date.getDay() == 6);
			let className;

			if (isToday) {
				className = 'today-highlight';
				y = (this.options.header_height + this.options.padding) / 2; // This is so the day highlight doesn't extend into the months header
			} else if (isWeekend) {
				className = 'weekend-highlight';
			} 

			if (isToday || isWeekend) {
				createSVG('rect', {
					x,
					y,
					width,
					height,
					class: className,
					append_to: this.layers.grid
				});	
			}
			x += this.options.column_width;
		}
	}
    }
```
And also changed the order of make_grid so the ticks would appear above the highlights:

```
	make_grid() {
		this.make_grid_background();
		this.make_grid_rows();
		this.make_grid_header();
		this.make_grid_highlights();
		this.make_grid_ticks();
	}
```

**Comment by zaubermann** [comment]
@netchampfaris Will you include this in a future update? I hope so :)

**Comment by prakash26sep** [comment]
Frappe, please consider this

**Comment by vaishyavivek** [comment]
@jeffberube any suggestion on how to apply your changes in an angular project? 
I tried adding these changes in node_modules/frappe_gantt/dist in an angular project with patch-package but the changes don't reflect. However, when I make the changes in a clone of frappe-gantt repo, the weekend highlights appear on index.html. 

Any suggestions what I could be missing?

**Comment by erpnext-tm** [comment]
This would be a really handy feature - but we have thus far been unable to follow the above guidance.  It would be great if someone could expand on the above guidance or push it into the core of Frappe?? @jeffberube

**Comment by LeeWheeler** [comment]
[ch-rigu] can you post your code please ? thanks

**Comment by bnhly** [comment]
@ch-rigu - what you've done looks great - hopefully you can share the code?  This is really useful and a push request would be brilliant - thank you

A slight further improvement would be to shade the background of the weekends - refer attached concept image
![snip](https://github.com/frappe/gantt/assets/131843742/cc8b32df-40b8-47b3-9cf5-f942e34a8b78)

**Comment by safwansamsudeen** [comment]
Hi everybody 👋🏽,

So this is closely related to #256 - except do you want to _disable_ (exclude from calculation) or just _highlight_?

**Comment by netchampfaris** [comment]
@safwansamsudeen We should treat both of these as separate features. A feature to highlight arbitrary periods. And another feature to exclude certain periods from calculation.
