### ISSUE TITLE
task._end.format('MMM D') does not work

### ISSUE THREAD

**Issue by lambdaq** [frappe/gantt#107]
https://frappe.io/gantt

Custom HTML in popup

`const end_date = task._end.format('MMM D');`

task._end is a Date object, it does not have the format method

**Comment by adedip** [comment]
@lambdaq you can use task.end and format with new Date() ;)

**Comment by dleunig** [comment]
Changing the line to
`const end_date = moment(task._end).format('MMM D');`
will fix the error

**Comment by safwansamsudeen** [comment]
In fact, you could use `date_utils` inside the library... but yeah, `moment` makes more sense.
