### ISSUE TITLE
How do I customize my language in options ?

### ISSUE THREAD

**Issue by dick3741** [frappe/gantt#109]
1. The only choice in the language is ‘cn, ru’, how do I add a custom language like this:
![image](https://user-images.githubusercontent.com/26373910/48175684-07a1e100-e348-11e8-85ee-618e39f80ece.png)
2. The gantt will have more white space at the bottom and popup cannot be closed by clicking in the space:
![image](https://user-images.githubusercontent.com/26373910/48239681-c7effd80-e40a-11e8-993b-39e40ba242f1.png)
3. I hope to add the feature of fixing the text on the left:
![image](https://user-images.githubusercontent.com/26373910/48239929-c115ba80-e40b-11e8-8941-377c51c0ff68.png)

**Comment by abin2011** [comment]
hi ,兄弟,你的左栏固定实现了吗?是怎么样实现的

**Comment by dick3741** [comment]
> hi ,兄弟,你的左栏固定实现了吗?是怎么样实现的

单独的div固定定位

**Comment by dick3741** [comment]
@abin2011 单独DIV固定定位

**Comment by Anurag810** [comment]
#117
