### ISSUE TITLE
Suggestion & Bug

### ISSUE THREAD

**Issue by hustcc** [frappe/gantt#11]
I use it in our two project, some suggestions below: 

1. `Custom configuration`: such as: color of task title, color of progress bar.

![image](https://cloud.githubusercontent.com/assets/7856674/23120578/ddce801a-f797-11e6-9b28-7bfd69e144b7.png)

The different color can help us to **distinguish different status** of task.

2. `Popup blocked by scrollbar`.

Thank for your reply and update.

**Comment by xskkk1777** [comment]
Really need these configurations in our project to make it more intuitive.

**Comment by hustcc** [comment]
Send pr in #12 .

**Comment by netchampfaris** [comment]
#14
