### ISSUE TITLE
Fixed grid header

### ISSUE THREAD

**Issue by discourseMonger** [frappe/gantt#115]
How can I make the grid-header (example element in attached image) fixed, so it doesn't scroll along with the rest of gantt chart?
![image](https://user-images.githubusercontent.com/30374372/50887240-f8e0b480-13f2-11e9-8c80-048a95397af9.png)

**Comment by jcjobin** [comment]
I wouldn't mind a way to do this, even if it means extending the library for some hack changes in the meantime.

**Comment by jcjobin** [comment]
For now, I have extended the Gantt class and implemented the changes from this commit: https://github.com/frappe/gantt/pull/100/commits/8b94aa97fdec373ac09d0ae6912e948f8fe9d0a1

**Comment by SaraBoutej** [comment]
> For now, I have extended the Gantt class and implemented the changes from this commit: [8b94aa9](https://github.com/frappe/gantt/commit/8b94aa97fdec373ac09d0ae6912e948f8fe9d0a1)

thank you so much it works for me
