### ISSUE TITLE
Tasks didn't scroll in the visible region

### ISSUE THREAD

**Issue by chenhongen** [frappe/gantt#118]
import frappe-grantt.js (which download from github)  by 
`<script src="dist/frappe-gantt.js"></script>`
Openning the index.html,Can't see tasks in the center of view.Need user scroll to find tasks.
![2019-01-28_134826](https://user-images.githubusercontent.com/16499303/51816869-7c5f3880-2303-11e9-8058-ad7ef4c0ab69.png)

---
But,import frappe-grantt.js (which download from frappe_io) by
```
	<script src="dist/moment.min.js"></script>
	<script src="dist/snap.svg-min.js"></script>
	<script src="dist/frappe-gantt.min.js"></script>
```
It's work well.
![2019-01-28_135005](https://user-images.githubusercontent.com/16499303/51816933-b6c8d580-2303-11e9-8e8f-51f6ac03205f.png)

**Comment by safwansamsudeen** [comment]
This seems to be a padding issue, probably fixed now. If you want to scroll to a particular date, #393 provides that.
