### ISSUE TITLE
View Mode: Week

### ISSUE THREAD

**Issue by LhexyRomero** [frappe/gantt#119]
Is it possible that every week 
should display like this

Week Upper: Jan 7 - 14, 2019
Week Lower: S M W TH F S

**Comment by LhexyRomero** [comment]
![image](https://user-images.githubusercontent.com/22766368/51824301-dc160d80-231c-11e9-8fa7-ab0494de0837.png)

This what i did but it only display every M = Monday.

**Comment by ayushnawani** [comment]
@LhexyRomero did you get the solution? I am also looking for the same

**Comment by petergreco** [comment]
This would require modification to a few function in the code, and localisation. So its a feature request.

Would you always want each week to start on Sunday for each project?

Might be a bigger rewrite if more flexibility in formatting headings is important, or are there a standard set of formats of headings we can define?

**Comment by safwansamsudeen** [comment]
@LhexyRomero I don't fully get the feature req here.

As I see it, two separate things:
1. You want to modify the upper/lower text
2. You want to start from Sunday?

1 sounds good, but 2: isn't the start date dynamically generated? I don't think it's always Monday.
