### ISSUE TITLE
The popup does not drag along with the bar

### ISSUE THREAD

**Issue by markaw375** [frappe/gantt#122]
When using the frappe version from Github it does not work like in the example from frappe.io. If you click the bar then the popup shows up and next if you drag the bar the popup should be sticked to the end of the bar and moved but it's not.

Github code:
![screen shot 2019-02-13 at 10 52 57](https://user-images.githubusercontent.com/30589074/52703149-fd623500-2f7d-11e9-8786-416a0a1e79ba.png)

Frappe.io demo example (correct):
![screen shot 2019-02-13 at 10 53 10](https://user-images.githubusercontent.com/30589074/52703180-0b17ba80-2f7e-11e9-8c05-8661c6e0ae12.png)

**Comment by SergeyMiracle** [comment]
any news on this issue?

**Comment by mikeott** [comment]
Same issue here. The number of inconsistencies between the demo page and the actual repo is frustrating. Is this project abandoned?

**Comment by SergeyMiracle** [comment]
@mikeott last activity on on 19 Jun 2020

i'm using dhtmlx-gantt - works nice

**Comment by safwansamsudeen** [comment]
> Same issue here. The number of inconsistencies between the demo page and the actual repo is frustrating. 

Yeah, we're working on aligning them.

> Is this project abandoned?

Well, it's alive now ;).

**Comment by safwansamsudeen** [comment]
In #393, we decided to make a click of the bar _hide_ the popup - so this feature is no longer relevant.
