### ISSUE TITLE
Prevent drag & resize in configuration

### ISSUE THREAD

**Issue by adedip** [frappe/gantt#125]
I can't find how, so I'm assuming is not possible to disable drag and resize in configuration.
That would be nice.

**Comment by evildeveloper** [comment]
Hi,
In case you're still interested, I've just tested it and it works on Chromium 73 and Firefox 66.

Go to [gantt/frappe-gantt.js](https://github.com/frappe/gantt/blob/13f579f4b6318e20d70b6d16efd59a984e0132c5/dist/frappe-gantt.js#L1614) (this is the direct link to the line on the repo in the master branch, your version may vary)

and set is_dragging to false as follows

`$.on(this.$svg, 'mousedown', '.bar-wrapper, .handle', (e, element) => {
            const bar_wrapper = $.closest('.bar-wrapper', element);`

`            if (element.classList.contains('left')) {
                is_resizing_left = true;
            } else if (element.classList.contains('right')) {
                is_resizing_right = true;
            } else if (element.classList.contains('bar-wrapper')) {
                //is_dragging = true;
               // set is_dragging to false
                is_dragging = false;
            }`

Best regards

**Comment by leonliang33** [comment]
This workaround works but I think this should have a proper fix / configuration feature.
It's very common to want to disable the whole dragging aspect and having to change it in source code directly is less than ideal

**Comment by pdsuk** [comment]
To disable dragging, I added...

```
            $('.bar-wrapper').on('mousedown', (e, element) => {
                e.preventDefault();
                e.stopPropagation();
            });

```

to my pages javascript after initiazlizing the component.

To disable the resizing, it should be:

```
            $('.handle').on('mousedown', (e, element) => {
                e.preventDefault();
                e.stopPropagation();
            });
```

Hope this helps...  👍🏻
