### ISSUE TITLE
Hiding popup only changes opacity (blocks click functionality)

### ISSUE THREAD

**Issue by totemhands** [frappe/gantt#127]
When you call the hide_popup function it only changes the opacity of the popup to 0 which hides it from view. 

This causes problems as the element still exists on top of anything else (just invisible) which prevents the click functionality of anything behind it.

e.g. I can't click the "Deployment" bar in the image below as the popup still sits in the way even though its invisible:

![image](https://user-images.githubusercontent.com/9084351/55790340-0bcb5980-5ab4-11e9-92ab-e83ba05efee2.png)

**Comment by petergreco** [comment]
I had this issue to, but its easily fixed, although I think one of the PR's will ultimately fix it.

Until then, I have added the following simple lines;
this.parent.style.pointerEvents = "auto";
this.parent.style.pointerEvents = "none";

Put it in the relevant spot as follows;

class Popup {
..
  show(options) {
  ...
  // show
  this.parent.style.opacity = 1;
  //fix for popup not being inactive on mouse events
  this.parent.style.pointerEvents = "auto";
  ...
}
hide() {
        this.parent.style.opacity = 0;
        //fix for popup not being inactive on mouse events
        this.parent.style.pointerEvents = "none";
}
}

**Comment by marcojuliusrei** [comment]
It's been almost 4 years now and I don't think there is an easy solution for this yet. Thanks for @petergreco for the pointer pointerEvents, this is my solution for this issue.



	setTimeout(function () {
		$('.bar-group').on('click', function (params) {
			gantt_chart.popup_wrapper.style.pointerEvents = "auto";
		})
		gantt_chart.popup.hide = function(){
			this.parent.style.opacity = 0;
			this.parent.style.pointerEvents = "none";
		}
	}, 1500);

I added **setTimeout** so that it will wait few seconds before the chart is loaded.

**Comment by safwansamsudeen** [comment]
Fixed now after #393 as popups come after hover.
