### ISSUE TITLE
Is this library being maintained or looking for maintainers?

### ISSUE THREAD

**Issue by kaiomagalhaes** [frappe/gantt#129]
I am using this library at my company and there are a few fixes we will be doing internally, and I would like to know if it is worth it creating PRs since I'm unsure if the current owner is maintaining it.

**Comment by partofthething** [comment]
Also wondering this. If it's not being maintained and you end up forking it and fixing a few of the big issues please direct us to your fork! I really like the style of this lib as shown on the demo page but can't get it working like that with the repo.

**Comment by manosbatsis** [comment]
Same here, if you end up forking let us know

**Comment by kaiomagalhaes** [comment]
I just noticed that there was a merge yesterday by @diegodurrod.

@diegodurrod would you be able to answer this issue? I'm currently creating a Gantt lib based on this library, and I would rather have it incorporated here instead of having it split. I'm mainly improving the code and fixing some bugs

**Comment by diegodurrod** [comment]
Hello @kaiomagalhaes ,

I'm not maintain this library, but, I thought the same as you: I'm creating a custom Gantt chart based on Frappe Gantt and I found some bugs in the code. I forked this library and I created a PR with the bugfixes, the bugfixes was accepted by Frappe team and merged it to master branch.

Cheers
