### ISSUE TITLE
BUG: Lenght can't be set shorter than 1 unit set by change_view_mode()

### ISSUE THREAD

**Issue by S-ed** [frappe/gantt#13]
![frappe-gantt](https://cloud.githubusercontent.com/assets/3008353/24124825/92805868-0dd6-11e7-9832-cd3961a2cc11.gif)

**Comment by zonaut** [comment]
Is this project still actively maintained? I see some commits but don't see actual problems getting fixed like this one which seems a basic functionality of this project.
