### ISSUE TITLE
Not working IN IE 11

### ISSUE THREAD

**Issue by VikasChaturvedi87** [frappe/gantt#134]
I have to support IE 11, and its not working there. Even https://frappe.io/gantt is not loading example Charts.

Can you guys please response quick so that I can decide which tool to use.

Thanks!.

**Comment by ryanlin1986** [comment]
Any update on this?

**Comment by petergreco** [comment]
First problem seems to be that IE 11 does not support default parameters. But I imagine there are a lot of Issues as IE11 doesn’t support all of the ECMAScript 6 features.

Is the project going to rewrite code for IE11?

**Comment by safwansamsudeen** [comment]
@netchampfaris do you think we should support IE? I vote no, as MS itself has officially discontinued.

**Comment by netchampfaris** [comment]
@safwansamsudeen You are right, we shouldn't support IE11.
