### ISSUE TITLE
Drag is choppy in firefox

### ISSUE THREAD

**Issue by jcjobin** [frappe/gantt#135]
Firefox 66.0.5 seems to have problems with dragging a task. 

Not entirely sure what is causing the issue. But the demo does not have this problem in Firefox. The same local project works fine in Chrome.

![drag_problem_firefox](https://user-images.githubusercontent.com/11465133/57935437-2d301a00-7898-11e9-951c-d44d6f322fa3.gif)

**Comment by WurstMitBrot** [comment]
Just search for offsetX and offsetY and replace it with clientX and clientY.

**Comment by jcjobin** [comment]
> Just search for offsetX and offsetY and replace it with clientX and clientY.

Took me a while to come across this again. Why was it ever offsetX/Y in the first place? Thanks though!
