### ISSUE TITLE
Print a Gantt Chart or Download Gantt Chart as JPG or PNG. Fix the Gantt Header

### ISSUE THREAD

**Issue by SukantaBhattacharyya** [frappe/gantt#136]
Hi 

I have plugged in the Frappe Gantt chart in one of our project two view the task progress. In addition we have two requirement with the Frappe Gantt chart as following:

a) To fix the Header of the displayed Gantt and the bars will scroll under the fix header
b) To take a print out of the displayed Gantt in PDF or to download the displayed Gantt chart as JPG or PNG format

Please help in this regards....

**Comment by safwansamsudeen** [comment]
Thanks for opening an issue!

a) see #115.
b) see #294
