### ISSUE TITLE
Size of activity bar cannot be smaller than the view column rather than a day minimum

### ISSUE THREAD

**Issue by petergreco** [frappe/gantt#141]
Hi guys, great stuff on this. I'm not proficient on github, so I thought this was the best place for my suggestion.

Just a small thing, I found that when the options match the view type i.e. "Month", "Week", the bar size cannot shrink down to less than that period.

I found that it is down to the single line in update_bar_position() .. where the last if statement has;
If(width && width >= this.gantt.options.column_width) ...

This probably shouldn't concern itself with the column width unless you start dividing it to get the day resolution. But the get_snap.. function run prior does all of this for you, I think its probably just best to leave it as;
If(width && width >= 0)
And let the function prior to its call manage the minimum sizes and snaps.

Cheers,
Pete

**Comment by safwansamsudeen** [comment]
Fixed today ;).
