### ISSUE TITLE
How to no display popup when click task. 

### ISSUE THREAD

**Issue by srcker** [frappe/gantt#144]
I don't want to show popup when I click on a task.

**Comment by JonesM87** [comment]
I have been adding an empty custom popup:

custom_popup_html: function(task) {
      return ``;
    }

**Comment by Uysim** [comment]
@JonesM87 it still show arrow

**Comment by imanwarsame** [comment]
For anyone else looking, the below worked for me to get rid of the arrow
`'.gantt-container .popup-wrapper .pointer': { borderColor: 'transparent' }`
