### ISSUE TITLE
How can we make it static chart.

### ISSUE THREAD

**Issue by erankitcs** [frappe/gantt#15]
hi team,

Just wanted to understand, how i can make this chart static. Means no drag and no time change etc. except on hover

**Comment by azappa** [comment]
I made a similar thing, resolved with simple css lines:
```stylus
#gantt
  pointer-events none
```

**Comment by erankitcs** [comment]
thanks a lot azappa . it works for me. I wanted to stop slider and time change only but it stopped all action. Please let me know if you have any solution for the same.

i have another question here, i was platting the gantt with date format : YYYY-MM-DD HH:mm  but seems outcome reverse in terms of headers division i,e. when i am putting time as 9:30 , its platting against 21:30 division instead of 9:30 and if i m putting 15:30 then its platting against 3:30 division of day. Do you have any solution make both in sync.

Thanks in advance for your help.

**Comment by seeeeew** [comment]
I'm doing it like this:

```javascript
function stopEvent(event) {
	event.preventDefault();
	event.stopPropagation();
}

new Gantt(id, tasks, {
	on_view_change: function() {
		var bars = document.querySelectorAll(id + " .bar-group");
		for (var i = 0; i < bars.length; i++) {
			bars[i].addEventListener("mousedown", stopEvent, true);
		}
		var handles = document.querySelectorAll(id + " .handle-group");
		for (var i = 0; i < handles.length; i++) {
			handles[i].remove();
		}
	}
});
```
This disables editing while preserving other interactions.

**Comment by JuFrolov** [comment]
```javascript
function draw() {
    draw_bar();
    
    if (gt.config.bar.progress)
        draw_progress_bar();
    draw_label();
               
    if (gt.config.bar.resizing)
         draw_resize_handles();
}
```

**Comment by netchampfaris** [comment]
@JuFrolov Can you send a PR so we can add it to the core?

**Comment by JuFrolov** [comment]
@netchampfaris As soon as I have free time, I will do it.

**Comment by ThomasKuhlmann** [comment]
@netchampfaris 
Hi,
just wondering, was this option ever included in the charts? I can't find anything in the documentation or source code. If not, would it be possible to add a flag which disables resizing/dragging and percentage changes? (Great work btw, love this library!)

**Comment by Anurag810** [comment]
@JuFrolov can please open the pull request for the fixes
