### ISSUE TITLE
Can't seem to find a way to enable view mode

### ISSUE THREAD

**Issue by zeddysoft** [frappe/gantt#150]
<img width="1237" alt="Screenshot 2019-10-20 at 1 11 06 PM" src="https://user-images.githubusercontent.com/6921756/67159364-5e2ae400-f33b-11e9-89b6-aa4925da94c6.png">
Hi, i'm trying out gantt chart in my angular app but i can't seem to get the view mode to display as attached, only the gantt displayed.

Please help.

**Comment by citylims** [comment]
I'm fairly certain those buttons aren't part of the library.
So you will need to add your own button and fire an event which calls change_view_mode()

**Comment by mikeott** [comment]
Drop this below the gantt target div:

```
<div class="btn-group" role="group">
	<button type="button" class="btn btn-sm btn-light">Quarter Day</button>
	<button type="button" class="btn btn-sm btn-light">Half Day</button>
	<button type="button" class="btn btn-sm btn-light">Day</button>
	<button type="button" class="btn btn-sm btn-light active">Week</button>
	<button type="button" class="btn btn-sm btn-light">Month</button>
</div>
```

...and into your JS...

```
gantt_chart.change_view_mode('Week');
$('.btn-group').on('click', 'button', function() {
      $btn = $(this);
      var mode = $btn.text();
      gantt_chart.change_view_mode(mode);
      $btn.parent().find('button').removeClass('active');
      $btn.addClass('active');
});
```

**Comment by safwansamsudeen** [comment]
This is only for the demo - not part of the framework.
