### ISSUE TITLE
disable drag

### ISSUE THREAD

**Issue by RahulShahUI** [frappe/gantt#151]
can we disable the dragging feature?

**Comment by jappyjan** [comment]
i solved this by calling refresh(tasks) with the current tasks inside the "on_drag" handler.

**Comment by RahulShahUI** [comment]
@jappyjan thanks for the reply.

i have added onDrag event with this library but still not working. You can check code in below codesandbox.

https://codesandbox.io/s/epic-greider-vvrv1

**Comment by CrisGarcis** [comment]
i need this

**Comment by Thimows** [comment]
Any updates on the feature request?

**Comment by erkankamazoglu** [comment]
The problem is solved if you take this.bind_bar_events comment line, which is called by the bind_events() method in frappe-gantt.js. Both the progress bar and task movement are disabled.

**Comment by John-F-C2** [comment]
I came across this same issue recently, this fork added a draggable option to easily disable.
https://github.com/Alisher778/frappe-gantt-extended
