### ISSUE TITLE
Cannot read property 'setAttribute' of null

### ISSUE THREAD

**Issue by doresearch** [frappe/gantt#152]
当数据呈现下述格式时候
![image](https://user-images.githubusercontent.com/12741598/67916036-71f20800-fbcf-11e9-907a-23b85194a394.png)
可以渲染到页面呈现为
![image](https://user-images.githubusercontent.com/12741598/67916086-9352f400-fbcf-11e9-8981-9cc9fb343f00.png)
但是当点击时候出现
```
Cannot read property 'setAttribute' of null
```
发现是没有.handle.left元素
 
需要兼容这种情况下的点击

**Comment by safwansamsudeen** [comment]
I think this is fixed now, sorry for the delay.
