### ISSUE TITLE
Is it possible to define minimum and/or maximum date bounds? 

### ISSUE THREAD

**Issue by BorisAng** [frappe/gantt#169]
We are plotting a Gantt chart with some data which could be significantly new or old/historic data. 
The chart seems to always draw the time scale until today's / the current date, hence, when using historic data there is a lot of empty space to the right of the last bar (see image)

![image](https://user-images.githubusercontent.com/24811561/76311063-0419c380-62c8-11ea-8f24-f3fbea8763ac.png)

Is there anyway to define the bounds of the displayed dates, for example, something like `gantt.setBounds(minDate, maxDate)?

**Comment by zhampu** [comment]
This Info could be very useful for me too

**Comment by Hienz** [comment]
I found something to this: in the index.js file there is a function called setup_gantt_dates(), there you can change the "paddings". No external solutions found so far.

**Comment by zhampu** [comment]
@Hienz thanks fro the info.
could you be more specific on how to change this?

**Comment by Hienz** [comment]
Below the ` // add date padding on both sides` comment, just change the gantt_start and the gantt_end in your desired view mode.

**Comment by safwansamsudeen** [comment]
Configurable padding was implemented today in #387!
