### ISSUE TITLE
Custom css bar colors not working

### ISSUE THREAD

**Issue by jainpradeep** [frappe/gantt#175]
Hi,

custom bar color not applying with css

let tasks = { id: 1, custom_class: 'cc-red' ... }

.cc-red g rect { fill: red !important; }

dosent work

**Comment by cdoug88** [comment]
Try this instead:

```.cc-red .bar-progress { fill: red !important; }```

**Comment by balain** [comment]
Hello. Thank you for this great library! Very useful.

I had the same problem with custom CSS classes now working. After updating the draw_bar() function, line 544: from: `class: 'bar'` to `class: 'bar ' + (this.task.custom_class || '')` it seems to work for me.

I'll keep testing it and if it holds up, will submit a pull request later this week.

**Comment by safwansamsudeen** [comment]
I don't think this is faced anymore.
