### ISSUE TITLE
Bar events not working

### ISSUE THREAD

**Issue by NeoGmTak** [frappe/gantt#179]
When I want to resize or move a bar on the chart I've got this error :
Uncaught TypeError: can't access property "$bar", this.gantt.get_bar(...) is undefined

Due to this error resize and move events are not working.

I've install the project with npm and just instanciate the chart like this :
```javascript
var tasks = [
    {
        id: 'Task 1',
        name: 'Redesign website',
        start: '2016-12-28',
        end: '2016-12-31',
        progress: 20,
        dependencies: 'Task 2, Task 3',
        custom_class: 'bar-milestone' // optional
    }
];

var gantt = new Gantt('#frappe-gantt', tasks, {
    on_click: function (task) {
        console.log(task);
    },
    on_date_change: function(task, start, end) {
        console.log(task, start, end);
    },
    on_progress_change: function(task, progress) {
        console.log(task, progress);
    },
    on_view_change: function(mode) {
        console.log(mode);
    }
});
```

It's the example in the documentation nothing more

**Comment by aruldd** [comment]
Hi, I am facing the same issue. How did you fix it?

**Comment by web-developer032** [comment]
problem is you have a dependency of a task that doesn't exist their.
