### ISSUE TITLE
Firefox+IE problem when dragging, resizing and changing progress

### ISSUE THREAD

**Issue by rog101** [frappe/gantt#182]
I downloaded the current version of gantt chart from github and have the following problem in Firefox: when dragging the bar, it disappears. the same happens when resizing. Also in firefox, changing the progress doesn't work.

This all works on your website https://frappe.io/gantt but not in the downloaded version

**Comment by ELI7VH** [comment]
This happens for me too. I noticed all the react libraries turn all their `task` objects into instances of a Task class, do we have to roll a Task class with setters and getters to make this work?

**Comment by TobyOoO** [comment]
This is still happening on Firefox 82.
