### ISSUE TITLE
[Feature request] Horizontal scroll with touch

### ISSUE THREAD

**Issue by ctwhome** [frappe/gantt#183]
Add the ability to grab and drag the horizontal scroll with the mouse or touch when it is outside the tasks.  

![image](https://user-images.githubusercontent.com/4195550/86360686-ffac5880-bc72-11ea-8afb-a8ce7281ce15.png)

**Comment by monis8khan** [comment]
Did you find it's solution? or anyone else found it solution?

**Comment by Leio123** [comment]
Drag right,left
frappe-gantt/src/index.js 
update function 'bind_grid_click()'
bind_grid_click() {
        // add
        let is_dragging = false;
        let x_on_start = 0;
        // ...
        $.on(
            this.$svg,
            this.options.popup_trigger,
            '.grid-row, .grid-header',
            () => {
                this.unselect_all();
                this.hide_popup();
            }
        );
        // add
        $.on(this.$svg, 'mousedown', '.grid-row, .today-highlight', e => {
            is_dragging = true;
            x_on_start = e.offsetX;
            if (this.$svg.parentElement) {
                this.$svg.parentElement.style.cursor = 'move';
            }
        });

        $.on(this.$svg, 'mousemove', '.grid-row, .today-highlight', e => {
            if (!is_dragging) {
                return;
            }
            const dx = e.offsetX - x_on_start;
            const parent_element = this.$svg.parentElement;
            if (!parent_element) return;
            parent_element.style.cursor = 'move';
            parent_element.scrollLeft += dx / 1.5;
            x_on_start = e.offsetX
        });

        document.addEventListener('mouseup', e => {
            if (this.$svg.parentElement) {
                this.$svg.parentElement.style.cursor = 'default';
            }
            is_dragging = false;
            x_on_start = 0;
        });
        // ...
    }

**Comment by Leio123** [comment]
Drag right,left
frappe-gantt/src/index.js
update function 'bind_grid_click()'
`    bind_grid_click() {
        // add
        let is_dragging = false;
        let x_on_start = 0;
        // ...
        $.on(
            this.$svg,
            this.options.popup_trigger,
            '.grid-row, .grid-header',
            () => {
                this.unselect_all();
                this.hide_popup();
            }
        );
        // add
        $.on(this.$svg, 'mousedown', '.grid-row, .weekend-highlight, .today-highlight', e => {
            is_dragging = true;
            x_on_start = e.offsetX;
            if (this.$svg.parentElement) {
                this.$svg.parentElement.style.cursor = 'move';
            }
        });

        $.on(this.$svg, 'mousemove', '.grid-row, .weekend-highlight, .today-highlight', e => {
            if (!is_dragging) {
                return;
            }
            const dx = e.offsetX - x_on_start;
            const parent_element = this.$svg.parentElement;
            if (!parent_element) return;
            parent_element.style.cursor = 'move';
            parent_element.scrollLeft += dx / 1.5;
            x_on_start = e.offsetX
        });

        document.addEventListener('mouseup', e => {
            if (this.$svg.parentElement) {
                this.$svg.parentElement.style.cursor = 'default';
            }
            is_dragging = false;
            x_on_start = 0;
        });
        // ...
    }
`

**Comment by vanboom** [comment]
This would be very intuitive way to scroll the chart via mouse or touch device.  Would you reconsider opening  this issue and possibly adopting this feature/behavior?
