### ISSUE TITLE
Define start day for week view mode

### ISSUE THREAD

**Issue by kremersa** [frappe/gantt#186]
Hello,

When using the 'Week' view mode like so:
```
var gantt = new Gantt('#gantt', tasks);
gantt.change_view_mode('Week');
```

I always get a start day on Saturdays. 
I'm looking for a way to start the week on Mondays.
Can someone give me a hint? I was not able to find an option for this.

Cheers,
Sascha

**Comment by safwansamsudeen** [comment]
I think it depends on what your data is. Padding is automatically assigned based on your view.
