### ISSUE TITLE
AngularJS Implementation w/ Data Binding

### ISSUE THREAD

**Issue by teracomp** [frappe/gantt#19]
Is there any issue with using this cool Gantt chart component in an AngularJS (1.5+) project?

**Comment by shyamal890** [comment]
That is what I was going to ask. This looks awesome however, would love to implement in Angular

**Comment by hustcc** [comment]
React version is [here](https://github.com/hustcc/gantt-for-react).

Angular is not my skill range.

**Comment by netchampfaris** [comment]
@teracomp Please try it out with Angular and share your experience!

**Comment by mariohmol** [comment]
hi,.. just for curiosity.. anyone heard about an angular2 wraper?

**Comment by safwansamsudeen** [comment]
#105 and #300 are Angular-related queries, if someone comes across this.
