### ISSUE TITLE
How can I remove icons from a task when mouse is over it ? 

### ISSUE THREAD

**Issue by lx2pwnd** [frappe/gantt#192]
When I move the mouse over a task, appears some icons to resize the task and resize the progress like as the first task in the image below. 

<img width="353" alt="Schermata 2020-08-23 alle 17 44 56" src="https://user-images.githubusercontent.com/33377086/90984719-16867180-e577-11ea-8f01-4a700b6b5e4b.png">

I want to hide this icons and show the task like in the image below. How can I do this ? Thanks a lot.

**Comment by mikeott** [comment]
Use CSS:

```
.handle-group {
	display: none;
}
```
