### ISSUE TITLE
Can I add fields/columns to the chart?

### ISSUE THREAD

**Issue by AndrewSithole** [frappe/gantt#195]
How can I add columns to the chart like "id" and "label" in the image below. Is this possible?

![Screenshot 2020-08-29 at 09 26 15](https://user-images.githubusercontent.com/7779130/91631471-f244ed80-e9d9-11ea-9d14-e0d78f4a2c9d.png)

**Comment by maudrid** [comment]
Yes, please, how can this be done?

**Comment by Peter-Pear** [comment]
I would really like someone could lead the way to implement this.

Thank you!

**Comment by William-Wildridge** [comment]
@AndrewSithole did you ever find a good workaround for this?

**Comment by AndrewSithole** [comment]
Yes. Sorry for the long silence. I went into the JS and edited the functions that create the SVGs. Its not the best workaround for large charts but it works fine for my case. Happy to share the code if you're still interested

**Comment by William-Wildridge** [comment]
Thank you Andrew, I personally ended up going with FullCalendar with allows for custom resources, but I am sure other folks would find your solution handy : )

**Comment by PeterPaulG** [comment]
**@AndrewSithole** would you share your solution with us? I could definitely need it for my project.
Thank you very much.

**Comment by AndrewSithole** [comment]
I have added my code here: https://github.com/AndrewSithole/gantt. Its not yet good enough for me to create a pull request but its usable with very few modifications.

Its important to note that in its current state, you'll need to define a columns array when you instantiate the chart.

**Comment by Igore-ADJOTIN** [comment]
@AndrewSithole can we have an exemples please ?

**Comment by safwansamsudeen** [comment]
Thanks folks - I've opened the extended issue #389.

**Comment by newpost** [comment]
> Like this?
> 
>  gantt-frappe-table-leftpanel.mp4

Thank you so much for providing this video. Could you please share the implementation code if available? I really appreciate your help! @tuliomportela 👍
