### ISSUE TITLE
How to use frappe gantt online

### ISSUE THREAD

**Issue by dhyunk** [frappe/gantt#197]
Hello!
I'm trying to use this web gantt chart tool.

But it returns me error when I use it on html.

Here is my code: 
<script src="frappe-gantt.min.js"></script>

And this is my error content:
net::ERR_ABORTED 404 (Not Found) 

Can I import the library online?

Thank you !

**Comment by dhyunk** [comment]
I mean, how to import the library online?

**Comment by tejask432** [comment]
there is no online library.
you need to download the file and include it.

**Comment by dhyunk** [comment]
> there is no online library.
> you need to download the file and include it.

OK!
I got it!
Thank you!
