### ISSUE TITLE
New feature: MIlestones?

### ISSUE THREAD

**Issue by poVoq** [frappe/gantt#2]
It would be nice if certain tasks (with multiple dependencies) could be marked as "milestones" with a special visibility. Related to this, it would be nice if there were task groups (or sub-tasks) that could be collapsed. Then the overall task should be shown with the earliest start date and the last end date of all included tasks.

**Comment by Dbonejones** [comment]
https://github.com/frappe/gantt/issues/9

**Comment by hustcc** [comment]
Maybe https://github.com/frappe/gantt/pull/12 can reach this feature.

**Comment by netchampfaris** [comment]
#14

**Comment by kevincam3** [comment]
Did this ever get added? I could use this feature
