### ISSUE TITLE
Internet explorer

### ISSUE THREAD

**Issue by nickwilliams999** [frappe/gantt#20]
Hi,

Thank you for coding such a great gantt charting tool!

Is there any way of / or a fix for it working on Internet explorer? 

Nick

**Comment by nickwilliams999** [comment]
Any ideas?

**Comment by nickwilliams999** [comment]
Hi,

Wanted to post an update for others that may be wanting / needing Frappe gantt to work in Internet explorer 9 to 11.

We used the babeljs polyfill script to resolve the issue.

https://babeljs.io/docs/usage/polyfill/ 

This now fully works as before and also on the above version of IE 9.

Hope this help.

Nick

**Comment by bryan-c-oconnell** [comment]
@nickwilliams999 - were you able to get the `custom_popup_html` to bind & fire in IE 11? If so I'd love to know how. I have the chart rendering just fine in IE, and the popups work for me in Opera and Chrome, but not IE.

**Comment by nickwilliams999** [comment]
Hi Bryan-c-oconnell,

We ended up not using the custom_popup_html as we made the whole of the gantt chart read-only.

**Comment by bryan-c-oconnell** [comment]
Drat! Ok, thanks for the reply. I definitely need the popups ...

**Comment by nickwilliams999** [comment]
Let me know if you have any luck with it bryan-c-oconnell

**Comment by netchampfaris** [comment]
@nickwilliams999 Good to hear that it worked for you!

Unfortunately, I don't plan to support IE, so if you have found methods to make it work, please add it to the readme and send a PR 😄
