### ISSUE TITLE
How to specify the start end dates shown in chart

### ISSUE THREAD

**Issue by sviswana** [frappe/gantt#201]
Even if the chart ranges from 10/1 - 10/5 for example, the gantt chart automatically seems to add days before and afterward. Is there a way to adjust it?

**Comment by tejask432** [comment]
draw_resize_handles()- checkout this method update_bar methods called here

**Comment by zaubermann** [comment]
Is there a documentation somewhere to look up these methods?

**Comment by safwansamsudeen** [comment]
Date padding is intentional.
