### ISSUE TITLE
view_mode: 'Quarter Day'   time is not accurate ，

### ISSUE THREAD

**Issue by chenyuxinxin** [frappe/gantt#208]
{
        start: '2018-10-01 20:00:22',
        end: '2018-10-04 08:12:33',
        name: 'Redesign website',
        id: "Task 0",
        progress: 50
    },    this.time is not accurate  show in 'Quarter Day'  view_mode:
![image](https://user-images.githubusercontent.com/51556249/104870296-169e6800-5983-11eb-8bdd-785d1dac33bd.png)

**Comment by luca-vercelli** [comment]
I think I found the bug. The two following lines are swapped:

        const x_pos = {
            'Quarter Day_lower': this.options.column_width * 4 / 2,
            'Quarter Day_upper': 0,

should be

        const x_pos = {
            'Quarter Day_lower': 0,
            'Quarter Day_upper': this.options.column_width * 4 / 2,

**Comment by luca-vercelli** [comment]
The same bug applies to "Half Day" view

**Comment by luca-vercelli** [comment]
I now see that this issue is solved in @anto-christo PR

**Comment by safwansamsudeen** [comment]
Fixed today.

**Comment by chenyuxinxin** [comment]
我已经收到您的邮件，我会尽快阅读其相关事项，或者回复您。
