### ISSUE TITLE
WARN messages for npm install frappe-gantt

### ISSUE THREAD

**Issue by AleksandrSokolov** [frappe/gantt#210]
npm WARN saveError ENOENT: no such file or directory, open '/root/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/root/package.json'
npm WARN root No description
npm WARN root No repository field.
npm WARN root No README data
npm WARN root No license field.

**Comment by safwansamsudeen** [comment]
I don't think this applies anymore.
