### ISSUE TITLE
Date after dragging is not accurate

### ISSUE THREAD

**Issue by alexscott64** [frappe/gantt#211]
I've tried on both the master branch, and the code here:

https://github.com/frappe/gantt/pull/128/commits/51ea867a7183de2a3ffbafe8568257ad98a71e49

But after dragging a bar, the date (on click) and the date that gets sent back from `on_date_change` always ends up around 4 - 5 months behind, on the day view, week view, and month view.

Does anyone know what I can do?

**Comment by imanwarsame** [comment]
I have the same issue, is there a fix for this?

**Comment by safwansamsudeen** [comment]
I don't face this anymore - but many related bugs have been fixed in #382 and #387. 

Closing this for now, if anything comes up please comment/open an issue.
