### ISSUE TITLE
How to use .tick.thick property to show thick ticks weekly. 

### ISSUE THREAD

**Issue by monis8khan** [frappe/gantt#215]
![image](https://user-images.githubusercontent.com/59013221/110284946-55a47d80-8004-11eb-9dcd-4b84cb4dd789.png)

On **https://frappe.io/gantt** page it shows the thick lines weekly, but when I used the integration code, it gives thick line on each month's starting. 
![image](https://user-images.githubusercontent.com/59013221/110285205-b59b2400-8004-11eb-8e08-b6216e487a16.png)

**Code used**

Is there anyway to set it specifically to weeks? 
	var tasks = [..]//Array of tasks
	var gantt;
	var actions = {
		bar_corner_radius: 10,
		on_date_change: function (task, start, end) {
			window.parent.postMessage({ task, start, end }, "https://mywebsite");
		}
	};
	function changeDisplay(option) {
		gantt.change_view_mode(option)
	}
	function check() {
		gantt = new Gantt("#gantt", tasks, actions);
	}

**Comment by vaishyavivek** [comment]
+1

**Comment by safwansamsudeen** [comment]
This can be set specifically on view modes in v1.
