### ISSUE TITLE
Popup does not move with the task when dragging

### ISSUE THREAD

**Issue by mikeott** [frappe/gantt#220]
The [demo page](https://frappe.io/gantt) clearly shows the popup moving along with the task as you drag it, but the repo version does not have this functionality working.

Instead what happens is the popup remains where it is, making it feel as if dragging is broken. But if you keep dragging past the width of the popup then the dragging resumes, but that's not intuitive and for a long time I actually thought this was just broken.

This is how the official repo version works right now:

![gantt](https://user-images.githubusercontent.com/5625353/115036375-09e8cc00-9f00-11eb-826f-84f3724e7183.gif)

Does anyone have a solution to this? If the popup could be moved to above or below the task that would be one solution, but there doesn't appear to be any way to do that.

**Comment by linhnv2590** [comment]
search `$.on(this.$svg, 'mousedown', '.bar-wrapper, .handle', (e, element)` at frappe-gantt.js
then add `this.hide_popup();`
it's working for me

**Comment by safwansamsudeen** [comment]
Unnecessary after #393.
