### ISSUE TITLE
is it possible to ?

### ISSUE THREAD

**Issue by jlcurty** [frappe/gantt#23]
hi,

I'd like to use frappe/gantt as a graphical planning for rent items ,

is it possible to put several tasks on the same line ? 
is it possible to have a day view ? 

thanks for your support,
Jean-Louis

**Comment by netchampfaris** [comment]
@jlcurty Can you provide a mockup?
We already have a Day view mode.

**Comment by Deluxcode-paul** [comment]
I also need this. Mockup - http://prntscr.com/ihdhx7

**Comment by safwansamsudeen** [comment]
Duplicate of #95.
