### ISSUE TITLE
React frappe gannt 

### ISSUE THREAD

**Issue by ankitmverma** [frappe/gantt#231]
Please anyone help me out for using this options in React frappe gannt, I am unable to use this option in react project and please provide steps to use it in react js

 "header_height: 50,
  column_width: 30,
  step: 24,
  view_modes: ['Quarter Day', 'Half Day', 'Day', 'Week', 'Month'],
  bar_height: 20,
  bar_corner_radius: 3,
  arrow_curve: 5,
  padding: 18,
  view_mode: 'Day',   
  date_format: 'YYYY-MM-DD',
  custom_popup_html: null"
  
  
  I have used this to install frappe gannt 
  https://www.npmjs.com/package/frappe-gantt-react

**Comment by mariobdom** [comment]
Is not an official wrapper, so you should contact the creator of the wrapper. Im facing that issue too, so im using this lib in react

**Comment by safwansamsudeen** [comment]
Closing as `frappe-gantt-react` is not affiliated with Frappe. Hope it works for you now!
