### ISSUE TITLE
react frappe gantt - one month view at once

### ISSUE THREAD

**Issue by ankitmverma** [frappe/gantt#232]
is there any way or option to display one month at view rather than 1 and half month auto view

![002](https://user-images.githubusercontent.com/77949441/121304310-cf0c7e80-c919-11eb-9c15-f55d7e881bc9.png)

please share if have any options for react 

I have used this method for react frappe gantt - https://www.npmjs.com/package/frappe-gantt-react

**Comment by safwansamsudeen** [comment]
Do you mean padding? Yes, this has been implemented in #387.
