### ISSUE TITLE
Frappé Gantt only supports usage of a string CSS selector, HTML DOM element or SVG DOM element for the 'element' parameter

### ISSUE THREAD

**Issue by henryhu712** [frappe/gantt#236]
I create an element by the instructions of the repo:

    <svg id="gantt"></svg>

But get the error: Frappé Gantt only supports usage of a string CSS selector, HTML DOM element or SVG DOM element for the 'element' parameter.

How can I fix it?

**Comment by VarunPotti** [comment]
How did you fix this I am having the same error?

**Comment by ijazfx** [comment]
@henryhu712 how did you fix this issue?

**Comment by Dawnw3aver** [comment]
You should use gantt grawing function inside the DOMContentLoaded eventlistener. It works for me.
`<script>
        document.addEventListener("DOMContentLoaded", function () {
            var tasks = [
            {
                id: 'Task 1',
                name: 'Redesign website',
                start: '2016-12-28',
                end: '2016-12-31',
                progress: 20
            }]
            var gantt = new Gantt("#gantt", tasks);
        });

    </script>`
