### ISSUE TITLE
how to make id="date" as static while Y axis scroll

### ISSUE THREAD

**Issue by erankitcs** [frappe/gantt#24]
hi team,
i m finding a difficulty while doing Y-axis scroll. after some scroll, it becomes invisible. i want to make Date drig as static while Y axis scroll so that that will be always visible during scroll as well.
Pls suggest.
Thanks

**Comment by luofei2011** [comment]
I have achieved this by: https://github.com/luofei2011/gantt/commit/60bce12609d64509da631a5c708c8c2324a74133

**Comment by erankitcs** [comment]
Not needed now.
