### ISSUE TITLE
scrollbar at top and bottom

### ISSUE THREAD

**Issue by dgurovich** [frappe/gantt#248]
It would be nice to have a scrollbar at the top and bottom of the container for very large datasets.

also, is there a switch for a label column (fixed)?  I see that it was an issue and it was eventually closed.

**Comment by krishnaNcool** [comment]
have you got the solution

**Comment by be11o** [comment]
Please assign this to me :)

**Comment by m50S79sM6SRNp8Jn** [comment]
Why not use a vertical scrollbar?

**Comment by safwansamsudeen** [comment]
@dgurovich the second request will be covered in #115.

I think one would be covered by a set width, which is a good idea. Is that what you're asking?

**Comment by safwansamsudeen** [comment]
Scrollbars are available already.
![Uploading image.png…]()
