### ISSUE TITLE
It is possible to assign the same ressource more than one time to the same task bug/feature ?

### ISSUE THREAD

**Issue by pidou46** [frappe/gantt#254]
It is possible to assign assign the same resource more than one time to the same task.

Is this bug or a feature ? I don't see use a case but I may be wrong...

**Comment by dresende** [comment]
A scheduler for example. Or a task that happens in multiple non consecutive phases.

**Comment by safwansamsudeen** [comment]
What do you mean? I'm marking this as a duplicate of #269, but will reopen if needed.
