### ISSUE TITLE
Understanding details / tooltip 

### ISSUE THREAD

**Issue by PierreTardiveau** [frappe/gantt#255]
Hello,

I'm trying to understand how tooltip / details work.

When i go with the demo we can see that details are inside the SVG.

![image](https://user-images.githubusercontent.com/98959544/152351810-8ed6fda1-781d-494c-acc5-55d2c9e288dc.png)

When i clone repo to test it we can see that "tooltip" are outside SVG in popup-wrapper.

![image](https://user-images.githubusercontent.com/98959544/152351887-e9c66c22-0f8a-478b-9b58-f8ec106862ec.png)

why is that and how can i achieve to put tooltip inside SVG. (i juste clone it without change)

Thanks

**Comment by safwansamsudeen** [comment]
The popup isn't part of the SVG.
