### ISSUE TITLE
Exclude Weekend From Gantt

### ISSUE THREAD

**Issue by PeterPaulG** [frappe/gantt#256]
Hello everyone,

does anyone have a solution to extend the generated bars or parts of the bars in the Gantt that fall on a weekend by the number of days that actually fall on a weekend?

Thanks in advance for your help.

**Comment by m50S79sM6SRNp8Jn** [comment]
Not just weekends, but also flexibility for (public) holidays in different countries. With different css.
Holidays could be a separate array.

**Comment by safwansamsudeen** [comment]
@m50S79sM6SRNp8Jn Makes sense. How do you think we should show the holidays block? You say "different css".

This isn't extremely easy feat to implement, but I think it's a good one, so I hope you don't mind if we tackle it a little later.
