### ISSUE TITLE
Please consider Bar pinned on scroll 

### ISSUE THREAD

**Issue by zepvalue** [frappe/gantt#258]
I would love to propose the bar being pinned on scroll so the user don't lose track of what day/month they are looking at ! 

If it's a feature that most users need would be happy to help implementing it :)

**Comment by m50S79sM6SRNp8Jn** [comment]
Do you have such an example? Able to paste the image in the comments?

**Comment by safwansamsudeen** [comment]
Duplicate of #115, I believe.
