### ISSUE TITLE
Is it possible to make a condensed year view?

### ISSUE THREAD

**Issue by RayBB** [frappe/gantt#26]
I'd like to make it so I can view multiple years on one screen for showing things that mostly are on the scale a of a few months.

Basically I'd like to make something that could be condensed kinda like this:
![image](https://user-images.githubusercontent.com/921217/29228995-14ba9fb6-7eaa-11e7-9328-3ff05a041466.png)

**Comment by netchampfaris** [comment]
@RayBB I think it's possible. Just have to add another level of scaling.

**Comment by Anurag810** [comment]
The year view is available now #96
