### ISSUE TITLE
Node Sass deprecated

### ISSUE THREAD

**Issue by PolarNelvana** [frappe/gantt#263]
Frappe-Gantt depends on package node-sass. However, when I try to install node-sass using `npm install node-sass` I get an error saying saying "Node Sass version 7.0.0 is incompatible with ^4.0.0"
Node-sass is deprecated and frappe-gantt should be updated to use another package.
https://stackoverflow.com/questions/70281346/node-js-sass-version-7-0-0-is-incompatible-with-4-0-0-5-0-0-6-0-0
https://www.npmjs.com/package/node-sass

**Comment by andyxmai** [comment]
Ran into the same problem. Installing sass (`yarn add sass`) worked for me. I'm using create react app. See reference here: https://create-react-app.dev/docs/adding-a-sass-stylesheet/

**Comment by safwansamsudeen** [comment]
We do not use it anymore.
