### ISSUE TITLE
Moving the mouse outside the svg area while dragging a task

### ISSUE THREAD

**Issue by 3r1d** [frappe/gantt#265]
When dragging a task, 
moving the mouse outside the svg area and then coming back,
messes with date computation.

Any direction on how to fix this ?

Can this issue be solved using the following method  ?

https://stackoverflow.com/questions/41090785/how-to-prevent-losing-the-mouse-cursor-when-dragging-an-svg

**Comment by safwansamsudeen** [comment]
I cannot reproduce this - could you give more details?

**Comment by 3r1d** [comment]
Unfortunately, I don't have the dev environment anymore on my machine. I don"t remember exactly, but I think we found a way to circumvent the pb. I close the issue.
