### ISSUE TITLE
Align multiple gantt diagrams 

### ISSUE THREAD

**Issue by SebastianLJ** [frappe/gantt#266]
Is it possible to align multiple gantt diagrams to the same date (from a date picker) i have tried using the solution mentioned in this ticket: https://github.com/frappe/gantt/issues/112. But as can be seen on the picture below the months does not align. The month displacement is consistent no matter the date selected

![frappe_example](https://user-images.githubusercontent.com/37780699/164475736-5b51abd6-e207-4923-9491-b40ad39bd931.PNG)

**Comment by VietFDS** [comment]
Hi @SebastianLJ how you can chage Color of task

**Comment by safwansamsudeen** [comment]
@VietFDS use the `custom_class` option, and CSS to style.

I don't fully get this - things seem to be aligned for me in the pic.
