### ISSUE TITLE
Blocking possibility to change progress / date

### ISSUE THREAD

**Issue by lashus** [frappe/gantt#27]
Is it possible to set some settings in this library? To be precise - I'm looking for option to block possibility to change progress / date for certain users.

The best case scenerio would be:
new Gantt(container, tasks, {
   canChangeProgress: false,
   canChangeDate: false
});

**Comment by netchampfaris** [comment]
This feature should be easy to add. Contributions welcome.

**Comment by safwansamsudeen** [comment]
Duplicate of #351.
