### ISSUE TITLE
Cannot read property 'bindings' of null

### ISSUE THREAD

**Issue by romrom38** [frappe/gantt#277]
I've upgraded from babel 6 to babel 7 (i'm using laravel)
I was getting this error with both versions 0.3.0 and lastest (0.6.1) :

> ERROR in ./resources/assets/js/lib/frappe-gantt/src/index.js
> Module build failed (from ./node_modules/babel-loader/lib/index.js):
> TypeError: /var/www/html/portail/resources/assets/js/lib/frappe-gantt/src/index.js: Cannot read property 'bindings' of null
>     at Scope.moveBindingTo (/var/www/html/portail/node_modules/@babel/traverse/lib/scope/index.js:1040:13)
>     at convertBlockScopedToVar (/var/www/html/portail/resources/assets/js/lib/frappe-gantt/node_modules/babel-plugin-transform-es2015-block-scoping/lib/index.js:139:13)
>     at PluginPass.VariableDeclaration (/var/www/html/portail/resources/assets/js/lib/frappe-gantt/node_modules/babel-plugin-transform-es2015-block-scoping/lib/index.js:26:9)
>     at newFn (/var/www/html/portail/node_modules/@babel/traverse/lib/visitors.js:177:21)
>     at NodePath._call (/var/www/html/portail/node_modules/@babel/traverse/lib/path/context.js:53:20)
>     at NodePath.call (/var/www/html/portail/node_modules/@babel/traverse/lib/path/context.js:40:17)
>     at NodePath.visit (/var/www/html/portail/node_modules/@babel/traverse/lib/path/context.js:100:31)
>     at TraversalContext.visitQueue (/var/www/html/portail/node_modules/@babel/traverse/lib/context.js:103:16)
>     at TraversalContext.visitQueue (/var/www/html/portail/node_modules/@babel/traverse/lib/context.js:109:21)
>     at TraversalContext.visitQueue (/var/www/html/portail/node_modules/@babel/traverse/lib/context.js:109:21)
>     at TraversalContext.visitMultiple (/var/www/html/portail/node_modules/@babel/traverse/lib/context.js:72:17)
>     at TraversalContext.visit (/var/www/html/portail/node_modules/@babel/traverse/lib/context.js:129:19)
>     at traverseNode (/var/www/html/portail/node_modules/@babel/traverse/lib/traverse-node.js:24:17)
>     at NodePath.visit (/var/www/html/portail/node_modules/@babel/traverse/lib/path/context.js:107:52)
>     at TraversalContext.visitQueue (/var/www/html/portail/node_modules/@babel/traverse/lib/context.js:103:16)
>     at TraversalContext.visitSingle (/var/www/html/portail/node_modules/@babel/traverse/lib/context.js:77:19)

So I'm upgraded the following packages :
```
npm install -D @babel/cli
npm install -D @babel/preset-env
npm install -D babel-loader@latest
npm install -D sass-loader@^12.1.0
npm install -D @babel/core
npm install -D @vue/babel-preset-app
npm install -D @vue/cli-plugin-babel
npm install -D sass-loader@latest
```

Added a webpack config
vi webpack.mix.js
```
let mix = require('laravel-mix');
mix.copyDirectory('resources/assets/fonts', 'resources/assets/sass/fonts');
mix.js('resources/assets/js/app.js', 'public/js')
  .sass('resources/assets/sass/app.scss', 'public/css')
  .vue({ version: 2, extractVueStyles: true })
  .options({
    processCssUrls: false
  });
mix.babelConfig({
  presets: [
    "@babel/preset-env",
 ]
});
```

And created a babel config   :
vi .babelrc
```
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "useBuiltIns": "usage",
        "corejs": {
          "version": 3,
          "proposals": false
        },
        "targets": {
          "ie": "11"
        }
      },
      "@vue/cli-plugin-babel"
    ]
  ]
}
```

Now it gets compiled but I'm getting the following error :
app.js:90019 
       Uncaught (in promise) RangeError: Maximum call stack size exceeded
    at _typeof (app.js:90019:52)
    at _typeof (app.js:90019:112)
    at _typeof (app.js:90019:112)
    at _typeof (app.js:90019:112)
    at _typeof (app.js:90019:112)
    at _typeof (app.js:90019:112)
    at _typeof (app.js:90019:112)
    at _typeof (app.js:90019:112)
    at _typeof (app.js:90019:112)
    at _typeof (app.js:90019:112)

Which debugs as :
```
function _typeof(obj) {
    "@babel/helpers - typeof";
    return _typeof = "function" == typeof Symbol && "symbol" == _typeof(Symbol.iterator) ? function(obj) {
        return typeof obj === "undefined" ? "undefined" : _typeof(obj);
    } : function(obj) {
        return obj && "function" == typeof Symbol && obj.constructor === Symbol && obj !== Symbol.prototype ? "symbol" : typeof obj === "undefined" ? "undefined" : _typeof(obj);
    }, _typeof(obj);
}
```

I've tried almost everything I could find on the web regading this problem but still out of luck...
Has anyone got past this problem ?

Regards,

**Comment by safwansamsudeen** [comment]
Hey @romrom38 👋🏽

Do you still face this?

**Comment by romrom38** [comment]
I think it was solved by an other dev in my team. I got out of this project so I can't confirm how it has been solved sorry... I guess it can be closed...
