### ISSUE TITLE
UX - .tick.thick & calendar year

### ISSUE THREAD

**Issue by jgtokyo** [frappe/gantt#280]
Extremely minor, but to improve UX / reduce mis-reading of the gantt chart, in monthly view most viewers expect quarters to align with calendar years (eg .tick.thick applied between Dec/Jan, not between Nov/Dec, etc).  Or at least for there to be an additional .tick.extra-thick at the end of calendar years in all views.

**Comment by safwansamsudeen** [comment]
Hey - there are already extra thick lines between quarters in the month view. We'll make them more prominent in the upcoming UI revamp.
