### ISSUE TITLE
Any plans to merge all these pull requests? Is this still maintained? 

### ISSUE THREAD

**Issue by marcelfolaron** [frappe/gantt#285]
I'd be happy to work with maintainers and help merge/review requests.

**Comment by ruslanchek** [comment]
Seems abandoned

**Comment by psu** [comment]
I would be interested in helping out on this as well. Maybe not with coding as much as admin stuff. 
What are the possibilities? Can we create a major fork and implement the PR from the last 3-4 years there?

**Comment by marcelfolaron** [comment]
I’m using it heavily in github.com/leantime/leantime

Happy to fork and work through PRs (Do they transfer somehow?) if there is
interest.

**Comment by marcelfolaron** [comment]
Started a new fork and will migrate some of the PRs. https://github.com/Leantime/gantt
If anyone wants to help let me know and I'll add you to the repo.

**Comment by psu** [comment]
Great, I'll check it out this weekend :)

**Comment by marcelfolaron** [comment]
I merged the first 3 or so Pull Requests. Will continue. It's kind of cumbersome to do though, so if you have PRs you want merged please create a new PR at https://github.com/Leantime/gantt

**Comment by m50S79sM6SRNp8Jn** [comment]
Your fork is way behind and last commit is over a year ago.

![image](https://github.com/frappe/gantt/assets/100518846/315d388f-15d6-433f-9426-0ef057da3cb8)

**Comment by safwansamsudeen** [comment]
Thanks, everybody. This repo is still maintained, yes. These PRs will be merged over the coming weeks.
