### ISSUE TITLE
Black SVG

### ISSUE THREAD

**Issue by raf924** [frappe/gantt#29]
Hi, so yeah when I try to render a gantt with:

```
import Gantt from '../../../node_modules/frappe-gantt/src/Gantt.js';

let tasks = [{
      id: 'Task 1',
      name: 'IMMO',
      start: '2017-06-01',
      end: '2017-06-02',
      progress: 10
    }];
    let gantt = new Gantt(this.ganttContainer.nativeElement, tasks);
```

The svg is created and from what I saw in the DevTools filled correctly but it's rendered black on the page: 
![image](https://user-images.githubusercontent.com/2406923/30748142-9b687468-9faf-11e7-93a8-8639626eb101.png)

Using Chrome V60.0.3112.113 64bits

Any help appreciated, thanks.

**Comment by raf924** [comment]
So apparently if I also include frappe.min.js in a script tag it does work.

**Comment by KingRial** [comment]
For some reasons it seem you are not including the CSS stylesheet ( which should be inside the library ).

**Comment by raf924** [comment]
omg I'm so dumb of course, I'm so used to using pure Javascript libraries I never even considered there was CSS to load.

Thanks

**Comment by pratyushatmindfire** [comment]
Incase youre using it in your Angular Project, I had the same issue. Tried many different places to put the CSS<link> and JS<script> tags in. 

What worked for me was putting the CSS and the JS path in the [styles] and [scripts] array of angular.json. Ive attached a screenshot for reference.

![image](https://user-images.githubusercontent.com/76472787/205505768-b819b22a-977c-4b03-a434-099f846e7f37.png)

**Comment by pratyushatmindfire** [comment]
Incase youre using it in a Angular Project, I had the same issue as yours which I resolved by putting the path to stylesheet and script of frappe-gantt library in the [styles] and [scripts] array of angular.json file. I've attached a screenshot for reference.


![image](https://user-images.githubusercontent.com/76472787/205506010-c19ca310-2086-4686-8d28-e69283df532d.png)
