### ISSUE TITLE
Providing a custom start date of the X-axis scale.

### ISSUE THREAD

**Issue by charity1475** [frappe/gantt#295]
For any View mode I will choose, the x-axis will start far behind and then I can scroll back. I need to specify a minimum date in the x-axis where the graph will start.
Please refer to this from chart3 js [HERE](https://www.chartjs.org/docs/latest/axes/#axis-range-settings)

**Comment by m50S79sM6SRNp8Jn** [comment]
Have you figured out how to do this?

**Comment by charity1475** [comment]
Yeah

**Comment by m50S79sM6SRNp8Jn** [comment]
Ok great. Possible to share your solution with us so we can learn from it?

**Comment by LeeWheeler** [comment]
I would also like to know your answer

**Comment by charity1475** [comment]
@m50S79sM6SRNp8Jn @LeeWheeler, Sorry i didn't mean i found a solution really. But I stopped using frappe/gantt.  The only possible way I saw was downloading a js dist file  and customizing this block: https://github.com/frappe/gantt/blob/1d024dcb55d3a150ca8c819985067f9a69ae80ba/dist/frappe-gantt.js#L1151C16-L1151C16

**Comment by LeeWheeler** [comment]
Thanks I will give it a try Sent from my iPhone XS Max 512GBOn 7 Nov 2023, at 23:32, Charity ***@***.***> wrote:﻿
@m50S79sM6SRNp8Jn @LeeWheeler, Sorry i didn't mean i found a solution really. But I stopped using frappe/gantt.  The only possible way I saw was downloading a js dist file  and customizing this block: https://github.com/frappe/gantt/blob/1d024dcb55d3a150ca8c819985067f9a69ae80ba/dist/frappe-gantt.js#L1151C16-L1151C16

**Comment by charity1475** [comment]
👍

**Comment by safwansamsudeen** [comment]
Currently, padding is automatically set based on the view mode (e.g. 7 days on each side for half day view). Do you want to customize this behavior?

**Comment by safwansamsudeen** [comment]
Will be fixed in #387.
