### ISSUE TITLE
Customised bar colour.

### ISSUE THREAD

**Issue by charity1475** [frappe/gantt#296]
I need to use a different color that blue, how can I specify that.

**Comment by m50S79sM6SRNp8Jn** [comment]
Use custom_class: 'bar-milestone' and update its fill value in css.
 
const activity2 =
{
id: uuid2,
name: activity name,
start: getFormattedDate(now),
end: getFormattedDate(endDate),
owner_id: 123, <==== add
progress: 100,//calculatePercentageProgress(startDate, endDate).toFixed(2),
dependencies: uuid1,
custom_class: 'bar-milestone' // optional
};
tasks.value.push(activity2);
