### ISSUE TITLE
Gant / Calender view inconsistencies - task (projects) 

### ISSUE THREAD

**Issue by johnlongland** [frappe/gantt#299]
### Information about bug

When I create a task that is set to start on 13-5-2022 and ending on 17-5-2022, I get inconsistent views when selecting the various viewing options.

I have some screenshots on the discussion thread that I created, where I asked for some assistance.

https://discuss.erpnext.com/t/gant-calender-view-inconsistencies/89733

Suggestion:
As seen on the last screen-shot, there is a : 12a-12a .. which I assume means "12am to 12am". This seem to suggest that there is a time involved - perhaps a default. Perhaps this "time" is interpreted differently in various views ?????
Perhaps the solution would be just to make the time-line date-input ( in task) , a date-time input ?? Just a thought.

### Module

projects

### Version

ERPNext 13.27.1

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
N/A
```

**Comment by safwansamsudeen** [comment]
@johnlongland thanks for reporting this! We will fix it soon.

**Comment by safwansamsudeen** [comment]
@johnlongland sorry for the delay. Fixed now!
