### ISSUE TITLE
非常好的gantt插件，希望加入分组样式

### ISSUE THREAD

**Issue by hawind** [frappe/gantt#30]
![image](https://user-images.githubusercontent.com/11567857/31049913-7dbd6e9c-a670-11e7-9d69-cf7a3d9a294c.png)

期待加入分组样式

**Comment by netchampfaris** [comment]
@hawind Would be nice if you could translate your query into English.

**Comment by ZeroHsu** [comment]
@netchampfaris nice gantt plugin , hope to add the "Task Group" function

**Comment by Anurag810** [comment]
Issue fixed #93
