### ISSUE TITLE
Error with Angular 15

### ISSUE THREAD

**Issue by alvarosinmarca** [frappe/gantt#300]
./node_modules/frappe-gantt/src/gantt.scss?ngGlobalStyle:1:0 - Error: Module parse failed: Unexpected token (1:0)
File was processed with these loaders:
 * ./node_modules/resolve-url-loader/index.js
 * ./node_modules/sass-loader/dist/cjs.js
You may need an additional loader to handle the result of these loaders.
> .gantt .grid-background {
|   fill: none;
| }

With Angular 14 work with it: https://github.com/frappe/gantt/issues/203#issuecomment-1315502431

**Comment by levi-anglepoint** [comment]
I have the same issue as well.

As a workaround you can go to node_modules/frappe-gantt/src/index.js and comment out "import './gantt.scss';" on line 7.
Then import the styles in your angular.json file.

**Comment by mmospanenko** [comment]
this is because package.json has wrong configuration ("main": "src/index.js",), try to import directly from dist js and css (via css imports - styles or in .scss)

`import Gantt from 'frappe-gantt/dist/frappe-gantt';`

**Comment by alvarosinmarca** [comment]
Thanks you @mmospanenko, i have a folk that work! https://github.com/alvarosinmarca/ngx-gantt

**Comment by Ciaran0** [comment]
Loading from dist doesnt seem to work for me. 
Is there any other work around or another way to fix this?

**Comment by levi-anglepoint** [comment]
> Loading from dist doesnt seem to work for me. Is there any other work around or another way to fix this?

Comment out line 7 in the node_modules/frappe-gantt/src/index.js, which says "import './gantt.scss';"

Alternatively this package is forked off of the frappe-gantt package and the import gantt.scss is already commented out. [frappe-gantt-angular15](https://www.npmjs.com/package/frappe-gantt-angular15)

**Comment by Ciaran0** [comment]
> > Loading from dist doesnt seem to work for me. Is there any other work around or another way to fix this?
> 
> Comment out line 7 in the node_modules/frappe-gantt/src/index.js, which says "import './gantt.scss';"
> 
> Alternatively this package is forked off of the frappe-gantt package and the import gantt.scss is already commented out. [frappe-gantt-angular15](https://www.npmjs.com/package/frappe-gantt-angular15)

Thank you!
