### ISSUE TITLE
Dependencies: moment

### ISSUE THREAD

**Issue by hustcc** [frappe/gantt#31]
Now, the dependencies moment is not `require` in the source code, so we need to import `moment.js` by script tag in html.

issues here on my project [gantt-for-react](https://github.com/hustcc/gantt-for-react/issues), see below.

**Comment by dineshbn** [comment]
Use expose_loader to load the moment if u use web pack in your project.this will solve this issue.

**Comment by ViktorSoroka** [comment]
Is this deliberately change to use global `moment`?

**Comment by dineshbn** [comment]
Yes, it  loaded the moment globally.

**Comment by hustcc** [comment]
Put moment into `peer`, and import it in the source code.

I think this way maybe better.

**Comment by hustcc** [comment]
You can submit your case on https://github.com/frappe/gantt/issues/31.

Or 

 - import `moment.js` in your html file with `script` tag.
 - add moment.js in webpack as global.

**Comment by hustcc** [comment]
All the issue https://github.com/hustcc/gantt-for-react/issues?q=is%3Aissue+is%3Aclosed is about the dependency of `moment`.

**Comment by netchampfaris** [comment]
`moment.js` is not a dependency anymore 😄

**Comment by hustcc** [comment]
release new version gantt-for-react, use gantt@^2.0.0 as dependence.
