### ISSUE TITLE
Progress bar handle not viewable on 0 or 100 percent progress

### ISSUE THREAD

**Issue by triumphhub** [frappe/gantt#310]
Thanks for the awesome work.
downloaded on 01/11/2023
Google Chrome
Progress bar handle not viewable on 0 or 100 percent progress. At the moment I'm having to auto reset to 3 and 97 percent to be able to use the progress slider.

Any help appreciated.

**Comment by m50S79sM6SRNp8Jn** [comment]
Can you take a screen shot + code so we can see it?

**Comment by dercin** [comment]
Same here:

<img width="160" alt="image" src="https://github.com/frappe/gantt/assets/26633107/6b1ca196-7e5a-4fe7-a2c8-50ce6e670c90">

**Comment by safwansamsudeen** [comment]
Fixed by #382.
