### ISSUE TITLE
Background-color of chart

### ISSUE THREAD

**Issue by CGWeb94** [frappe/gantt#314]
Hello, 

is it possible to change the background color of the gantt chart?

 I can only find information on how to recolor the individual bars.
 
I'm in the process of implementing a dark mode, so it would be nice if the background of the chart was dark.

**Comment by m50S79sM6SRNp8Jn** [comment]
Were you able to solve this yet? If so, please share. Thanks!

**Comment by CGWeb94** [comment]
> Were you able to solve this yet? If so, please share. Thanks!

Sadly not

**Comment by kagklis** [comment]
The background is not a single element. It's many <rect> tags inside the svg that form the grid. These have a class which has a fill attribute. If you inspect the DOM through the Elements tab you can see all the classes assigned to each element.

Not sure if there's a better way, but this worked for me:

```
.gantt .grid-row {
   fill: red; // or any other color of your choice
}
```

**Comment by CGWeb94** [comment]
This works for me too. 
Thank you @kagklis 👍
