### ISSUE TITLE
feature for fix the header when too much tasks is there

### ISSUE THREAD

**Issue by jeffersyuan1976** [frappe/gantt#316]
Hi, 
If too much tasks is there, maybe we should thinking about to make the header fixed at the top of the gantt chart?
Thanks.

**Comment by m50S79sM6SRNp8Jn** [comment]
I concur. Really this should be default behaviour since from the outset you would never know have many tasks would be part of the Gantt chart.

**Comment by safwansamsudeen** [comment]
Yup - a sticky header is a good feature to have. Duplicate of #115.
