### ISSUE TITLE
Not Closing properly when outside Clicking

### ISSUE THREAD

**Issue by Maduki-tech** [frappe/gantt#319]
I just found an Issue by testing this amazing Open source Gantt. 

The issue happens, when you press an element in the gantt. The popup opens to the right side. 
When you click anywhere on the left side of the popup the popup will close. but of you click under the popup or to the right side of it, it will not close.

Testet in the Demo. Error is still happening
Browser is Chrome

**Comment by safwansamsudeen** [comment]
Hey - that's weird.

It's actually not supposed to open _even when clicked on the left_. Currently (after the new PR is merged), only clicking on the header or the bar itself should subside the popup.

There were a few bugs related to this, but they've been ironed out. Closing this for now.
