### ISSUE TITLE
ReferenceError: moment is not defined

### ISSUE THREAD

**Issue by ajAnshul** [frappe/gantt#32]
I have tried this component with react but getting this error:

`ReferenceError: moment is not defined`

**Comment by dineshbn** [comment]
Use Expose-loader plug in  to load in web pack configuration file.

**Comment by paullbn** [comment]
@ajAnshul maybe this momentjs issue can help you:
 https://github.com/moment/moment/issues/4216

**Comment by netchampfaris** [comment]
`moment.js` is not a dependency anymore 😄
