### ISSUE TITLE
Allow Tasks to Be Editable

### ISSUE THREAD

**Issue by GartenMensch** [frappe/gantt#323]
It could be a nice extra for people how are trying to limit users to only "Their Task"

**Comment by m50S79sM6SRNp8Jn** [comment]
I also require this. Would be great if Frappe could add owner_id (or similar)

   const activity2 =
    {
        id: uuid2,
        name: `activity name`,
        start: getFormattedDate(now),
        end: getFormattedDate(endDate),
        **owner_id: 123, <==== add**
        progress: 100,//calculatePercentageProgress(startDate, endDate).toFixed(2),
        dependencies: uuid1,
        custom_class: 'bar-milestone' // optional
    };
    tasks.value.push(activity2);

**Comment by safwansamsudeen** [comment]
Hmm. By draggable - do you mean resizable? Like all edit functionality (progress, width, dates) being barred?

**Comment by GartenMensch** [comment]
> Hmm. By draggable - do you mean resizable? Like all edit functionality (progress, width, dates) being barred?

exactly.
Background on this was, I was thinking about updating the Vacation(and other stuff) planner. i thought it frappe gant would be a great starting point. Only Problem was i needed to restrict the editable functionalities like you said, only to the Row of the Logged in user

**Comment by safwansamsudeen** [comment]
@GartenMensch sounds good.

**Comment by lucfranken** [comment]
Was the method to set a bar to editable true/false ever implemented? It seems that it is checked off by #393 but in the documentation and code there does not seem to be any implementation. Is that correct?

This issues seems to be very specific: 

`owner_id: 123, <==== add
`

A flag like: isEditable for example might make more sense. Or multiple flags for the different activities. Then application logic is outside of your code. 

It looks like a check on this method would suffice:

```js
let tasks = [
  {
    id: '1',
    name: 'Redesign website',
    start: '2016-12-28',
    end: '2016-12-31',
    progress: 20,
    allowResizing: false,
    allowDragging: false,
  },
  ...
]
let gantt = new Gantt("#gantt", tasks);
```

https://github.com/frappe/gantt/blob/master/src/index.js#L1100

```js
$.on(this.$svg, 'mousedown', '.bar-wrapper, .handle', (e, element) => {

  if(!this.allowResizing) {
    return;
  }
  if(!this.allowDragging) {
    return;
  }
```

Or is there more to it? If not implemented yet would you be open for a pull?

Our use case: 

A projects schedule where some projects are already scheduled - cannot be edited anymore - but the others should be editable.

**Comment by safwansamsudeen** [comment]
I'm not sure that I understand you.

We have three config options for this, mentioned in the docs:

<img width="811" alt="Image" src="https://github.com/user-attachments/assets/b01626a0-152a-43c3-9136-75f321c3571e" />

**Comment by lucfranken** [comment]
Yes correct, those are for the Gantt as a whole correct?

Exactly the same idea but then per bar. So one bar is editable, the other one is not.

**Comment by safwansamsudeen** [comment]
Ah, would be happy to accept a PR.
