### ISSUE TITLE
progress bar and resize

### ISSUE THREAD

**Issue by STEPHANE-OKTO** [frappe/gantt#325]
I try to install frappe, but when I try to change the duration or the progress bar with the mouse  it doesn't change the length and position of the background.
Can you help me please ?
Stéphane

**Comment by luizfboss** [comment]
Hello! I'd like to help you with this issue. I'll do my best :)

**Comment by m50S79sM6SRNp8Jn** [comment]
Work fine for me. Please make a video and share relevant code example.

**Comment by leslietquinn** [comment]
Cannot change progress if 0 or 100, as per previous issues (0.3.0).

**Comment by safwansamsudeen** [comment]
@leslietquinn I can. (Try seeing this video in full screen)

https://github.com/user-attachments/assets/a15ac6dc-595e-48a7-87f1-3d0345ed15f5
