### ISSUE TITLE
Clicking tasks results in 100s of uncaught exceptions

### ISSUE THREAD

**Issue by cortnum** [frappe/gantt#329]
Whenever I try and click something in the Gantt chart, i get a bunch of uncaught exceptions. Hundreds.. I pasted a stack trace here

index.js:692 Uncaught TypeError: Cannot read properties of undefined (reading '$bar')
    at index.js:692:34
    at Array.forEach (<anonymous>)
    at SVGSVGElement.<anonymous> (index.js:691:18)
    at SVGSVGElement.<anonymous> (svg_utils.js:105:22)
(anonymous) @ index.js:692
(anonymous) @ index.js:691
(anonymous) @ svg_utils.js:105
index.js:745 Uncaught TypeError: Cannot read properties of undefined (reading '$bar')
    at index.js:745:34
    at Array.forEach (<anonymous>)
    at SVGSVGElement.<anonymous> (index.js:744:18)
(anonymous) @ index.js:745
(anonymous) @ index.js:744
index.js:734 Uncaught TypeError: Cannot read properties of undefined (reading 'group')
    at index.js:734:43
    at Array.forEach (<anonymous>)
    at HTMLDocument.<anonymous> (index.js:734:22)
(anonymous) @ index.js:734
(anonymous) @ index.js:734
67index.js:706 Uncaught TypeError: Cannot read properties of undefined (reading '$bar')
    at index.js:706:34
    at Array.forEach (<anonymous>)
    at SVGSVGElement.<anonymous> (index.js:705:18)

**Comment by cortnum** [comment]
To clarify, I am just following the standard example from the GitHub

**Comment by jonybekov** [comment]
Facing the same issue on Codesandbox

**Comment by safwansamsudeen** [comment]
Could you give more details of your env? I don't face this.

**Comment by karsumir** [comment]
> Could you give more details of your env? I don't face this.

I also facing this issue.
1. I'm using react and made wrapper
2. prepare some tasks(will call this `base tasks`) with useState 
3. `useEffect(()=>{ new Gantt("#gantt-container", tasks, options)},[tasks]}` to force refreshing while tasks are changed.
4. add new task to tasks
5. check tasks changed.
6. click any task of `base tasks`: no problem
7. click new added task: getting above exceptions

**Comment by iPopstop** [comment]
Can you check #392 ? This works for me

**Comment by safwansamsudeen** [comment]
Thanks, @iPopstop - will do.
