### ISSUE TITLE
view_mode Hour not merged into master branch yet, right?

### ISSUE THREAD

**Issue by qinrongx** [frappe/gantt#335]
As I tried to set the view_mode=Hour, the page inspect function reported hundreds of errors:
frappe-gantt.min.js:1 Error: <text> attribute x: Expected length, "NaN".

I checked the master branch and can't find the drop related to the 'view_mode'=Hour.
Please help to confirm, thanks.

**Comment by lettuceDestroyer** [comment]
You're right. I couldn't find it either. Generally it seems they don't like to merge contributions to the master branch so your best bet at the moment is to fork the repository and merge it yourself. At least that's what I did.

**Comment by safwansamsudeen** [comment]
Will merge soon.
