### ISSUE TITLE
What are the data types for each item in the task list? Is the example complete?

### ISSUE THREAD

**Issue by liaowentao1016** [frappe/gantt#337]

**Comment by m50S79sM6SRNp8Jn** [comment]
See https://frappe.io/gantt and in particular `custom_popup_html`

`var gantt = new Gantt('#gantt', tasks, {
	// can be a function that returns html
	// or a simple html string
	custom_popup_html: function(task) {
	  // the task object will contain the updated
	  // dates and progress value
	  const end_date = task._end.format('MMM D');
	  return `
		<div class="details-container">
		  <h5>${task.name}</h5>
		  <p>Expected to finish by ${end_date}</p>
		  <p>${task.progress}% completed!</p>
		</div>
	  `;
	}
});`
