### ISSUE TITLE
Now we have a wrapper for React :D

### ISSUE THREAD

**Issue by mohammed-io** [frappe/gantt#34]
Hi, I've created a wrapper for this awesome library
You can check it [here](https://github.com/mohammed-io/frappe-gantt-react)

🔢

**Comment by netchampfaris** [comment]
Now we have another wrapper for React https://github.com/hustcc/gantt-for-react

**Comment by mohammed-io** [comment]
@netchampfaris this is old, not updated, and uses id selector, mine uses the DOM element, plus mine built with TypeScript (we have ts definitions).
Well, there's some bugs, so mine will work better.
