### ISSUE TITLE
[Feature Request] Add Editable Property

### ISSUE THREAD

**Issue by m50S79sM6SRNp8Jn** [frappe/gantt#351]
https://github.com/frappe/gantt/issues/323

const tasks = [
  {
    id: 1,
    name: "Task 1",
    start: "2023-08-01",
    end: "2023-08-10",
    draggable: true, // This property allows the task to be dragged/moved
  },

**Comment by safwansamsudeen** [comment]
I don't quite get you. Drag it where? 

Currently, we already support dragging within a row - do you want the ability to disable that?

**Comment by safwansamsudeen** [comment]
@m50S79sM6SRNp8Jn is this actually the same request as #323?
