### ISSUE TITLE
[Feature Request] support set task as paused and continue

### ISSUE THREAD

**Issue by ishowman** [frappe/gantt#352]
# case
For example, I plan to spend 2 weeks to finish taskA.But  3 days later, I need to do taskB for it is more emergency.
So I wish to pause taskA and finish taskB firstly, and continue taskA after I finish taskB.

# expected
I wish the progress bar is still show in the same row, and I can clearly know the task was not done in a single duration（for example, the time of paused task is showwith gray background color）.

**Comment by safwansamsudeen** [comment]
Ignoring is supported now 🎊 .
