### ISSUE TITLE
[Documentation] Where is documentation at all?

### ISSUE THREAD

**Issue by angry-elf** [frappe/gantt#356]
Can't find anywhere

**Comment by albadedan** [comment]
I agree.
It is a bit of a pain to get started with, and it's not actually as customisable as they suggest, at least not easily.
Plus the recent merged pulls seem to mostly be about dates and languages, rather than fixing issues or adding functionality.

**Comment by Klaus-Valse** [comment]
I agree, if I find the time I want to make a tutorial for dummys like me on my github.
