### ISSUE TITLE
custom_class does not work

### ISSUE THREAD

**Issue by PartTimeDevPM** [frappe/gantt#360]
Hi All, first post so be gentle.

I have been using frappe Gantt for a while now and its been good. I've come to the point where I need to add different coloured bars in for baselines and forecast dates. However the custom_class is not working, I have tried most of the work arounds I have seen on here but  nothing has worked. 

Following the standard of add "custom_class:'bar-milestone" and update the css file does literally nothing.

Using the inspect tool I can see the CSS field is being read but the colour doesn't change.

Any help gratefully received .

**Comment by LeeWheeler** [comment]
Part time paste you code in here so we can have a look.
