### ISSUE TITLE
Help Me for set color bar is red if no any progress for thats date

### ISSUE THREAD

**Issue by nanndaputra08** [frappe/gantt#362]
Hello Guys and the Frappe Gantt team, I received a requirement for the project I am currently working on, where the requirement is to give a red mark on the progress bar of the Gantt chart for a job if on that date there is no progress for the job, for example, there is a planning work that starts on 1-Jan-2023 and ends on 31-Jan-2023, if on 1-Jan-2023 or even 2-Jan-2023 there is no progress report for the work then the bar will run on the Gantt progress bar The chart is red for example, but the progress for the work remains 0% "maybe I can display it with a label/task name", then if on 3-Jan-2023 there is a progress update for the work, for example 5%, then the progress bar will be blue appears starting from 3-Jan-2023 and for 1 and 2 Jan 2023 it remains red and if on the next date there is no progress report back for that date, then the bar on that date will be red too, please help if any of you can help me
<img width="937" alt="frappe gant" src="https://github.com/frappe/gantt/assets/45335314/3058ebce-ac04-4ac8-85d8-46a911c72609">

**Comment by LeeWheeler** [comment]
Hi show us what code you have written so that I can see what you have done.   [nanndaputra08]
