### ISSUE TITLE
[Issue] Events displayed 12 hours later than they really are

### ISSUE THREAD

**Issue by MartaWild** [frappe/gantt#369]
Hello! 
I was experimenting with the Gantt chart and noticed that there is an issue with displaying times of events. They appear 12 hours later than they really should be. 

Here are some screenshots. You can see that I have one event that starts at midnight on October 1st and ends at noon on October 3rd. The date string is also parsed correctly to a Date object, but on the chart it displays as noon on October 1st and **midnight on October 4th.**

I think the problem is in the label position calculation: https://github.com/frappe/gantt/blob/1d024dcb55d3a150ca8c819985067f9a69ae80ba/src/index.js#L545

This happens only in the "quarter day" and "half day" modes. 

```
var tasks = [
    {
        start: '2018-10-01 00:00:00',
        end: '2018-10-03 12:00:00',
        name: 'Redesign website',
        id: 'Task 0',
        progress: 20,
    },
];
var gantt_chart = new Gantt('.gantt-target', tasks, {
	on_click: (task) => {},
	on_date_change: (task, start, end) => {},
	on_progress_change: (task, progress) => {},
	on_view_change: (mode) => {},
	view_mode: 'Quarter Day',
	language: 'en',
});
```
![image](https://github.com/frappe/gantt/assets/47245850/83c33982-8b3e-43be-b952-80bf02f69bf8)

**Comment by safwansamsudeen** [comment]
Thanks for your detailed explanation! Will be fixed by #382.
