### ISSUE TITLE
Problem with dates while in MONTH view

### ISSUE THREAD

**Issue by slavenakolevaa** [frappe/gantt#375]
Hello,

I have a few tasks with some start and end date. The tasks (with dates and bars) are displayed correctly when I'm in DAY or WEEK view. If I switch to MONTH, the chart dates are not aligned with the tasks dates. 

For example, if the task starts on 2024-06-09 and ends on 2024-06-15, the Gantt displays it somewhere in October, the same year.
The date format is set to YYYY-MM-DD. 
![image](https://github.com/frappe/gantt/assets/16246328/8c8acfec-640a-4966-ba88-0fe69119edeb)

Does anyone know how to resolve the issue? 

Thank you in advance,

**Comment by safwansamsudeen** [comment]
@slavenakolevaa 👋🏽,

I don't quite get you - what is the issue? The chart dates are separate from the task dates. The former is influenced by the view you choose, the latter by your inputs.

What is the bug here?
