### ISSUE TITLE
Expand the Tasks whenever it is hover over on the Holiday

### ISSUE THREAD

**Issue by dineshbn** [frappe/gantt#38]
Can we expand the  Tasks whenever it is hover over on the Holiday Periods?

**Comment by netchampfaris** [comment]
What do you mean by expand tasks?

**Comment by Anurag810** [comment]
please follow the contribution guidelines, be more descriptive and also add screenshot (if any)  
![Screenshot 2019-04-29 at 11 53 59 AM](https://user-images.githubusercontent.com/32095923/56879261-8a913200-6a75-11e9-84b8-ad6f32371893.png)
