### ISSUE TITLE
Drag function for each task

### ISSUE THREAD

**Issue by chaelimheo** [frappe/gantt#383]
I'm so happy to hear that you're actively developing again.

My question is, Can I turn on and off the drag function for each task?
I don't want to turn off the drag function of the entire job. 
If there are A, B, and C tasks, can A and C be dragged and B tasks be set not to be dragged?

**Comment by safwansamsudeen** [comment]
By dragged, do you mean editable (width, dates, progress)?

If so, that's covered in #323.
