### ISSUE TITLE
Npm publish : Fix Github Actions

### ISSUE THREAD

**Issue by TheoLaperrouse** [frappe/gantt#399]
Hello, 

I really appreciate your library and all the work you have put into this project.

I use your project by downloading it from the npm registry, however the last publish on npm was two years ago. This means that the latest features are not available. It seems that this is due to Github actions (https://github.com/frappe/gantt/actions/workflows/publish.yml) which don't go as far as publishing on npm. It seems to be because of small lint issues.

Could you please update the various lint issues so that I can benefit from the latest versions of the library? This would help me enormously in my work.

Thank you very much for your understanding and help.

**Comment by TheoLaperrouse** [comment]
I think that run `yarn prettier` and upgrading the node version to 16 in `.workflow/publish.yml` fix the action.

**Comment by Dygitz** [comment]
ditto

**Comment by safwansamsudeen** [comment]
Fixed now! We also cleaned up our tooling today.
