### ISSUE TITLE
Baselines for planning audits?

### ISSUE THREAD

**Issue by poVoq** [frappe/gantt#4]
In the long run (but I guess that would require significant code changes) it would be awesome if there was an option to generate "baselines" i.e. snapshots of earlier planning stages that can be compared to the current time plan to identify common bottlenecks or planning mistakes etc.

**Comment by Deluxcode-paul** [comment]
+

**Comment by plamenh** [comment]
A quick suggestion on how you can implement this on your own:

Why don't you take the snapshot yourselves, i.e. save the tasks array to your database/storage of choice? Then you can retrieve and visualize it anytime you want.

For example:

1. submit your current tasks array to your backend and save it with a timestamp and a relation to an object (project probably...)
2. in each project, get a list of all timestamped related snapshots from your backend
3. render a select field and on selecting the relevant snapshot just switch the tasks prop to the snapshot data

**Comment by safwansamsudeen** [comment]
Sounds good... except where would you store the data?

Would export (see #294) fix your problem?
