### ISSUE TITLE
Some view mode don't fully fit gantt container

### ISSUE THREAD

**Issue by samuel-litzler** [frappe/gantt#401]
Hi ! Just look at the picture -> there is a big gap between the gantt and the scroll bar ^^'

- Branch : master
- Defaults tasks list of the index.html
- View mode -> Month or Year (of course it depends of the tasks)

![image](https://github.com/frappe/gantt/assets/24872653/d997cf8c-1371-4889-b41f-ec81a761e5a7)

**Comment by safwansamsudeen** [comment]
Thank you! Fixed today.
