### ISSUE TITLE
Today button position is wrong after resize

### ISSUE THREAD

**Issue by chiarapivetta** [frappe/gantt#402]
Hi,
The side header, which can contain the scroll to today button or the mode drop-down, has a fixed position relative to the screen. That means that when you resize the screen, the button won't be stuck to the left side of the header but it goes everywhere and might not be visible. 

Initial position:
![image](https://github.com/frappe/gantt/assets/38748810/7b2616bb-1b9a-4e58-9868-65061b16d8d5)

After resize:
![image](https://github.com/frappe/gantt/assets/38748810/3c36219f-3018-42c8-898f-9bde595a9518)
or:
![image](https://github.com/frappe/gantt/assets/38748810/bc8dfaa8-8ec9-458d-a8a7-1e8e2d107201)

**Comment by Klaus-Valse** [comment]
I have the same issue, including the leftmost currently displayed month.
<img width="943" alt="image" src="https://github.com/frappe/gantt/assets/17731529/5233a946-e8a5-41c3-bca3-ca082ae6ff89">

They both move with the scroll bar.

**Comment by safwansamsudeen** [comment]
Header issues were fixed in the leadup to v1.
