### ISSUE TITLE
Uncaught TypeError: $today is null

### ISSUE THREAD

**Issue by senti-mark-monteiro** [frappe/gantt#413]
I'm using the library from the latest commit on the `master` branch. I get the following error when using, or switching to, the day, week, month, or year view:

```
Uncaught TypeError: $today is null
    make_grid_highlights https://n-hqps3kizwvk2rlnpu72bojagq2qddn5zqadf6cq-0lu-script.googleusercontent.com/userCodeAppPanel:15945
    make_grid_extras https://n-hqps3kizwvk2rlnpu72bojagq2qddn5zqadf6cq-0lu-script.googleusercontent.com/userCodeAppPanel:15742
    render https://n-hqps3kizwvk2rlnpu72bojagq2qddn5zqadf6cq-0lu-script.googleusercontent.com/userCodeAppPanel:15715
    change_view_mode https://n-hqps3kizwvk2rlnpu72bojagq2qddn5zqadf6cq-0lu-script.googleusercontent.com/userCodeAppPanel:15630
    make_side_header https://n-hqps3kizwvk2rlnpu72bojagq2qddn5zqadf6cq-0lu-script.googleusercontent.com/userCodeAppPanel:15819
userCodeAppPanel:15945:13
```

The offending code is [here](https://github.com/frappe/gantt/blob/b7deffd53954ebae5c6dd77bdab54551ca1d17e8/src/index.js#L625C44-L625C54). It's not clear to me what element this line of code is attempting to find

```js
let $today = document.getElementById(date_utils.format(date).replaceAll(' ', '_'))
```

**Comment by senti-mark-monteiro** [comment]
Upon further consideration I have realized what is causing this error. This will happen when rendering the Gantt chart for historical or future data, and the current date is not included in the timeline at the top of the chart.

I will try to put together a PR to fix this

**Comment by Klaus-Valse** [comment]
Wait I think you duplicated my issue that I posted right before (https://github.com/frappe/gantt/issues/412). Maybe my documentation helps.

**Comment by mark-monteiro** [comment]
Ah yeah, looks like we opened duplicate issues. My PR #414 will fix both issues

**Comment by safwansamsudeen** [comment]
Thanks for calling this out, and apologies for the delay in fixing it!
