### ISSUE TITLE
Option to disable auto-moving dependencies

### ISSUE THREAD

**Issue by KebabRonin** [frappe/gantt#418]
It would be useful to be able to move events without moving their dependencies. (eg: task1 depends on task2 but is 1 week ahead, moving task2 will also move task1).

Adding an option to turn this off or customise the dependency moving behaviour would solve this issue (maybe it could be configurable, like enabling the current behaviour with a key shortcut or only on certain events).

**Comment by safwansamsudeen** [comment]
Implemented today! Please set `move_dependencies` to `false`.
