### ISSUE TITLE
[BUG] Dragging progress really fast to the left doesn't set progress to 0 

### ISSUE THREAD

**Issue by KebabRonin** [frappe/gantt#430]
Dragging the progress to the right seems to stop at 100% every time, but dragging to the left will stop at random points depending on how fast you were going.

![dragging example](https://github.com/user-attachments/assets/a57d38df-8dea-4453-8099-5f1078270d65)

(Tested on latest release 0.8.0)

**Comment by safwansamsudeen** [comment]
Fixed today, nice catch.
