### ISSUE TITLE
[Feature Request] Add an API/option to add more custom time scales

### ISSUE THREAD

**Issue by KebabRonin** [frappe/gantt#431]
Currently, all things depending on the time scale are big if/else trees, for each available time scale. This can make it tedious to add or modify view modes.

It would be nice to have a configuration object to get these settings from, so people can more easily add other time scales without the need to alter/search through the code.

The new option could look something like this:
```js
var gantt = new Gantt(div, tasks, {
   // ...
   view_modes: [
      {
         name: 'Hour',
         step: 3600, // in unix seconds
         snap_interval: 300, // snap task dates to 5 minute intervals
         upper_text: {
            x: 10, // offset from the 'base position'
            period: 3600 * 24, // repeat the upper text for each day
            text: 'DD', // using date_utils or in some date format
            column_width: 38 // using date_utils or in some date format
         },
         lower_text: {/* similar to upper_text */}
      },
      // ... more view modes
   ]
   }
}
```

**Comment by moradlarbi** [comment]
Can you assigne this issue to me please? i want to work on it

**Comment by safwansamsudeen** [comment]
Nice idea. I think the solution would require a lot of effort - which is fine, but there are more important things to fix and improve right now. 

What are the use cases for this? We provide almost every commonly used time period.

**Comment by safwansamsudeen** [comment]
Much thanks to @moradlarbi for his awesome work here.

**Comment by KebabRonin** [comment]
Use case is for any other custom time interval, like hourly, biweekly, minutely, etc.. This would be especially useful for setting the snapping interval to something custom, and setting the text interval.

It would also be useful to have the thick ticks configurable, as they can be used to convey different meanings (like start of week, which can usually be Monday or Sunday, or delimiting 2week sprints in a yearly view instead of the months).

**Comment by moradlarbi** [comment]
What do you mean by configuring ticks ? Do you mean to introduce parametre to precise what ticks represents?

**Comment by KebabRonin** [comment]
Yes, I was mainly referring to the thick ones, not necessarily the small ones for every day/month.

As in draw small ticks to delimit every day, and a thick tick to delimit every Friday/some other custom interval, different from the default.

I don't recall how it was implemented in frappe, but it's only a 'nice to have' feature, just an idea, not necessary to implement if there's more important things to do

**Comment by safwansamsudeen** [comment]
Nah, I think that should be easy to implement. Could you open an issue with more detail on what you want?
