### ISSUE TITLE
[Improvement] Bind gantt object to 'this' inside event handlers

### ISSUE THREAD

**Issue by KebabRonin** [frappe/gantt#433]
When using ```on_date_change``` or ```on_click```, there doesn't seem to be a way to access the gantt object without global variables. It would be nice to bind ```this``` to the gantt object, so the handlers may contain more complex behaviour (ex: highlighting all tasks with the same priority as the clicked task).

The fix would entail modifying the ```trigger_event``` in the ```Gantt``` class as follows:
```js
trigger_event(event, args) {
  if (this.options['on_' + event]) {
    this.options['on_' + event].apply(this, args); // Changed from apply(null, args);
  }
}
```

**Comment by safwansamsudeen** [comment]
Nice feature! 

Implemented, but note that you can't use arrow functions to access `this` - you have to change the `index.html` functions to be normally defined.

The demo has been updated accordingly.
