### ISSUE TITLE
Absence of gantt-container check for existing

### ISSUE THREAD

**Issue by ArtemOstapov** [frappe/gantt#436]
If i use own react wrapper the gantt-container div created 2 times with corresponding inside divs.

![22222222222222](https://github.com/user-attachments/assets/0a92e326-bcde-45c0-887e-033e317af501)

Could you plz add for that code checks for existing it like with svg you have 

```
// wrapper element
this.$container = document.createElement('div');
this.$container.classList.add('gantt-container');
```
to

```
// wrapper element
this.$container = document.querySelector('.gantt-container');

if (!this.$container) {
    this.$container = document.createElement('div');
    this.$container.classList.add('gantt-container');
}
```

and

```
// popup wrapper
this.popup_wrapper = document.createElement('div');
this.popup_wrapper.classList.add('popup-wrapper');
this.$container.appendChild(this.popup_wrapper);
```
to
```
 this.popup_wrapper = this.$container.querySelector('.popup-wrapper');

if (!this.popup_wrapper) {
    this.popup_wrapper = document.createElement('div');
    this.popup_wrapper.classList.add('popup-wrapper');
    this.$container.appendChild(this.popup_wrapper);
}
```

**Comment by safwansamsudeen** [comment]
What is the code you're using that gives this output?

**Comment by ArtemOstapov** [comment]
I'm using already other gannt lib, and quickly cant find that code

**Comment by safwansamsudeen** [comment]
Ah that's okay. We're actively developing Gantt tho (I now work at Frappe!) so you can be sure that Gantt will be fine from now on. LMK if you want to switch, I'd be glad to help out.

What other library are you using, and do you like it better? Could you give us some feedback? Thanks!
