### ISSUE TITLE
[v0.8.x]: cannot import in complex webpack-based workflows

### ISSUE THREAD

**Issue by tagliala** [frappe/gantt#439]
Hello,

I already have a PR for this, but I'm opening an issue for tracking purposes

After upgrading to v0.8.1, I was receiving an error related to a "missing export of `.`".

Since it is time consuming to provide a reproducible test case, I can point to some of the most recent issues related to the addition of `exports` to `package.json`:
- https://github.com/Choices-js/Choices/issues/1184
- https://github.com/Choices-js/Choices/issues/1184#issuecomment-2322861193

Ref: https://webpack.js.org/guides/package-exports/

I will submit a PR

**Comment by frustak** [comment]
Hello, I encountered an issue while using the "frappe-gantt" package with Vite. The error message I received was:

```sh
[ERROR] Failed to resolve entry for package "frappe-gantt". The package may have incorrect main/module/exports specified in its package.json: No known conditions for "." specifier in "frappe-gantt" package [plugin vite:dep-scan]
```

To resolve this, I modified the "exports" section in the package.json like this:
```json
"exports": {
    ".": {
        "require": "./dist/frappe-gantt.umd.js",
        "import": "./dist/frappe-gantt.umd.js"
    }
}
```

This change seems to have solved the issue!

**Comment by tagliala** [comment]
> "import": "./dist/frappe-gantt.umd.js"

Isn't supposed to be the `es` module file, as in #441?

> I'm not sure if this is related to this issue or not.

I'm confident it is, but I'm not a javascript developer

**Comment by frustak** [comment]
You're right, both options seem to work, and using the es module feels more appropriate in this context.

**Comment by tagliala** [comment]
@frustak can you please check if `"frappe-gantt": "tagliala/gantt#chore/import-directive-webpack"` works out of the box for you? I'll then remove the draft status here

**Comment by frustak** [comment]
Yes, it works out of the box for me.

**Comment by a-h** [comment]
Is there a workaround for this until the PR is merged?

**Comment by tagliala** [comment]
Did you try my fork?

https://github.com/frappe/gantt/issues/439#issuecomment-2376142487

**Comment by a-h** [comment]
I wasn't sure how to do that. I can't see an NPM package for it, and wasn't sure how `npm.lock` files etc. would work.

I was hoping there would be a way to tell `vite` to use the other import mechanism.

**Comment by tagliala** [comment]
> I wasn't sure how to do that. I can't see an NPM package for it, and wasn't sure how npm.lock files etc. would work.

Should be possible in this way:

In package.json

```diff
-  "frappe-gantt": "^0.8.0"
+ "frappe-gantt": "tagliala/gantt#chore/import-directive-webpack"
```

or, according to your package manager
```
npm add choices.js@tagliala/gantt#chore/import-directive-webpack
```

I don't know if there are ways in the host application package.json to override export directives.

Maybe `imports`?

https://nodejs.org/api/packages.html#subpath-imports

**Comment by a-h** [comment]
Thanks for your help. Adding a resolve section to my `vite.config.ts` also seemed to work:

```ts
  resolve: {
    alias: {
      'frappe-gantt': 'node_modules/frappe-gantt/dist/frappe-gantt.es.js',
    },
  },
```

With this in place, I can tell it to bypass the `package.json` and load the `es` directly. For the CSS, I could copy the CSS from the `dist` directory, and add `import './frappe-gantt.css'` to the `app/root.tsx`.

This seems to have the same effect as your fork.

**Comment by safwansamsudeen** [comment]
Thanks for your feedback here folks!
