### ISSUE TITLE
Adding tasks dynamically

### ISSUE THREAD

**Issue by bensialih** [frappe/gantt#44]
Hi Is there any way we can add tasks, then call the render or refresh function.
Also, How do I change the duration in the bar and re-render them.

Thank

**Comment by stvkas** [comment]
I ran into this issue today, too. You could add tasks just like you describe with the exposed `refresh` method. I've shared the update pattern I'm using in this [jsfiddle](https://jsfiddle.net/stvkas/jgtygxro/14/)
