### ISSUE TITLE
Frappe gantt chart display is not correct and change view mode is not working

### ISSUE THREAD

**Issue by Paulami31** [frappe/gantt#445]
The width of the container is cropping automatically, I cannot share my exact organizational code, but sharing the demo code, that is working with display, but mode change options are not working, in my original code I have sent you the ss before, the chart is cropping from right
 -

`<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Frappe Gantt Chart Example</title>
 <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/frappe-gantt/dist/frappe-gantt.css">
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <style>
    .gantt .bar-label {
      fill: #0335fc;
      font-size: 15px;
      font-weight: bold;
    }

    .zoom-buttons {
      position: absolute;
      top: 150px;
      right: 10px;
      display: flex;
      gap: 5px;
    }

    .zoom-buttons button {
      background-color: #fff;
      border: 1px solid #ccc;
      border-radius: 4px;
      padding: 5px 10px;
      cursor: pointer;
      font-size: 18px;
    }

    #zoom-in::before {
      content: "+";
    }

    #zoom-out::before {
      content: "-";
    }
  </style>
</head>

<body>
  <div id="gantt-chart" style="margin-bottom: 50px;"></div>
  <div class="zoom-buttons">
    <button id="zoom-in"></button>
    <button id="zoom-out"></button>
  </div>

  <script src="https://cdn.jsdelivr.net/npm/frappe-gantt/dist/frappe-gantt.umd.js"></script>
  <script>
    document.addEventListener('DOMContentLoaded', function () {
      const tasks = [
        {
          id: "Task 1",
          name: "Task 1",
          start: "2023-09-01",
          end: "2023-09-05",
          progress: 100,
        },
        {
          id: "Task 2",
          name: "Task 2",
          start: "2023-09-03",
          end: "2023-09-10",
          progress: 50,
        },
        {
          id: "Task 3",
          name: "Task 3",
          start: "2023-09-06",
          end: "2023-09-12",
          progress: 25,
        },
      ];

      try {
        var minDate = new Date(Math.min(...tasks.map(t => new Date(t.start))));
        var maxDate = new Date(Math.max(...tasks.map(t => new Date(t.end))));

        var gantt = new Gantt('#gantt-chart', tasks, {
        on_click: function (task) {
          var currentUrl = window.location.href;
          var baseUrl = currentUrl.substring(0, currentUrl.lastIndexOf('/'));
          var pageUrl = baseUrl + '/' + task.id.toLowerCase().replace(/\s/g, '-') + '/'; 
          window.location.href = pageUrl;
          console.log("Page Url:", pageUrl);
        },
          on_date_change: function (task, start, end) {
            console.log(task, start, end);
          },
          on_progress_change: function (task, progress) {
            console.log(task, progress);
          },
          on_view_change: function (mode) {
            console.log('View mode changed:', mode);
          },
          header_height: 50,
          column_width: 30,
          step: 24,
          view_modes: ["Quarter Day", "Half Day", "Day", "Week", "Month"],
          bar_height: 30,
          bar_corner_radius: 3,
          arrow_curve: 5,
          padding: 18,
          view_mode: "Week",
          date_format: "YYYY-MM-DD",
          language: "en",
          custom_popup_html: null,
          start_date: minDate,
          end_date: maxDate
        });

        $('#zoom-in').click(function () {
          if (gantt.options.view_mode === 'Day') {
            return;
          } else if (gantt.options.view_mode === 'Week') {
            gantt.change_view_mode('Day');
          } else if (gantt.options.view_mode === 'Month') {
            gantt.change_view_mode('Week');
          } else if (gantt.options.view_mode === 'Year') {
            gantt.change_view_mode('Month');
          }
        });
        $('#zoom-out').click(function () {
          if (gantt.options.view_mode === 'Day') {
            gantt.change_view_mode('Week');
          } else if (gantt.options.view_mode === 'Week') {
            gantt.change_view_mode('Month');
          } else if (gantt.options.view_mode === 'Month') {
            gantt.change_view_mode('Year');
          }
        });
      } catch (error) {
        console.error('Error initializing Gantt chart:', error);
      }
    });
  </script>
</body>

</html>`

this is a html file, the view modes are not working on clicking on the + and - button, which was working before.

an error is also coming in console -
Error initializing Gantt chart: TypeError: Cannot destructure property 'x' of 'this.computeGridHighlightDimensions(...)' as it is undefined.
![Screenshot 2024-09-23 125852](https://github.com/user-attachments/assets/51ae2eb9-1bb7-4e74-b331-c2aa98f0e89d)

**Comment by Paulami31** [comment]
closing it now.

**Comment by safwansamsudeen** [comment]
@Paulami31 does this work yet? Gantt is under active development now again.
