### ISSUE TITLE
Month and week mode is not working in frappe gantt

### ISSUE THREAD

**Issue by Paulami31** [frappe/gantt#451]
![image](https://github.com/user-attachments/assets/b89a1cca-22db-4dff-80ce-87416f45cfc9)
getting the above error for month and week view.
please anyone help me out to fix this.

@safwansamsudeen

**Comment by safwansamsudeen** [comment]
Hi,

Sorry for the delay. I've joined Frappe now, so things should be much smoother :). 

We'll push a fix by tomorrow.

**Comment by safwansamsudeen** [comment]
Could you share your code?
