### ISSUE TITLE
Default year span is not changing.

### ISSUE THREAD

**Issue by Paulami31** [frappe/gantt#452]
The year mode always shows a span of 6 years always, how can I update the graph so that only the years span max and min we are displaying should only be there?
for eg: the below graph is showing year from 2021-2027 , but the tasks date are from 2023-2024, I want only those years to be displayed .
I've tried to update the gantt_start and gantt_end values and re-rendered the chart, but seems not working.
`<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Frappe Gantt Chart Example</title>
 <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/frappe-gantt/dist/frappe-gantt.css">
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

</head>

<body>
  <div id="gantt-chart" style="margin-bottom: 50px;"></div>
  <div class="zoom-buttons">
    <button id="zoom-in"></button>
    <button id="zoom-out"></button>
  </div>
  <style>
    .gantt .bar-label {
      fill: #0335fc!important;
      font-size: 15px;
      font-weight: bold;
    }

    .zoom-buttons {
      position: absolute;
      top: 550px;
      right: 10px;
      display: flex;
      gap: 5px;
    }

    .zoom-buttons button {
      background-color: #fff;
      border: 1px solid #ccc;
      border-radius: 4px;
      padding: 5px 10px;
      cursor: pointer;
      font-size: 18px;
    }

    #zoom-in::before {
      content: "+";
    }

    #zoom-out::before {
      content: "-";
    }

    .today-button {
      display: none;
    }
  </style>
  <script src="https://cdn.jsdelivr.net/npm/frappe-gantt/dist/frappe-gantt.umd.js"></script>
  <script>
    document.addEventListener('DOMContentLoaded', function () {
      const tasks = [
        {
          id: "Information about the OOS Batches file used for modeling.",
          name: "Information about the OOS Batches file used for modeling.",
          start: "2023-07-03",
          end: "2024-07-31",
        },
        {
          id: "Unfolded Genealogy",
          name: "Unfolded Genealogy",
          start: "2022-07-02",
          end: "2024-07-31",
        },
        {
          id: "Adding Group/Stage Eigenvectors",
          name: " Adding Group/Stage Eigenvectors",
          start: "2024-07-03",
          end: "2024-07-31",
        },
      ];

      try {
        var minDate = new Date(Math.min(...tasks.map(t => new Date(t.start))));
        var maxDate = new Date(Math.max(...tasks.map(t => new Date(t.end))));

        var gantt = new Gantt('#gantt-chart', tasks, {
        on_click: function (task) {
          var currentUrl = window.location.href;
          var baseUrl = currentUrl.substring(0, currentUrl.lastIndexOf('/'));
          var pageUrl = baseUrl + '/' + task.id.toLowerCase().replace(/\s/g, '-') + '/'; 
          window.location.href = pageUrl;
          console.log("Page Url:", pageUrl);
        },
          on_date_change: function (task, start, end) {
            console.log(task, start, end);
          },
          on_progress_change: function (task, progress) {
            console.log(task, progress);
          },
          on_view_change: function (mode) {
            console.log('View mode changed:', mode);
          },
          header_height: 50,
          column_width: 30,
          step: 24,
          view_modes: ["Quarter Day", "Half Day", "Day", "Week", "Month"],
          bar_height: 30,
          bar_corner_radius: 3,
          arrow_curve: 5,
          padding: 18,
          view_mode: "Year",
          date_format: "YYYY-MM-DD",
          language: "en",
          custom_popup_html: null,
          start_date: minDate,
          end_date: maxDate
        },
      
     );
     gantt.gantt_start = minDate;
     gantt.gantt_end = maxDate;

     gantt.change_view_mode(gantt.options.view_mode);
        $('#zoom-in').click(function () {
          if (gantt.options.view_mode === 'Day') {
            return;
          } else if (gantt.options.view_mode === 'Week') {
            gantt.change_view_mode('Day');
          } else if (gantt.options.view_mode === 'Month') {
            gantt.change_view_mode('Week');
          } else if (gantt.options.view_mode === 'Year') {
            gantt.change_view_mode('Month');
          }
        });
        $('#zoom-out').click(function () {
          if (gantt.options.view_mode === 'Day') {
            gantt.change_view_mode('Week');
          } else if (gantt.options.view_mode === 'Week') {
            gantt.change_view_mode('Month');
          } else if (gantt.options.view_mode === 'Month') {
            gantt.change_view_mode('Year');
          }
        });
      } catch (error) {
        console.error('Error initializing Gantt chart:', error);
      }
    });
  </script>
</body>

</html>`

![image](https://github.com/user-attachments/assets/0a3a37d2-7d91-4164-847a-36d1480ec9f9)

**Comment by safwansamsudeen** [comment]
You can use the `padding` parameter in the view mode.
