### ISSUE TITLE
custom_popup_html javascript seems not to work

### ISSUE THREAD

**Issue by jurerejc** [frappe/gantt#453]
Hi,

I am struggling with custom_popup_html to define my custom popup, but it seems not to work and the popup is always the same-attached image.

![Capture](https://github.com/user-attachments/assets/30f710d0-ed92-4532-a55a-c7dbd72f5a85)
 I am using

`<head>    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/frappe-gantt/0.8.1/frappe-gantt.umd.js"></script>
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/frappe-gantt/0.8.1/frappe-gantt.css" />   
</head>

....

                    custom_popup_html: function (task) {
                        const start_date = task._start.toLocaleDateString();
                        const end_date = task._end.toLocaleDateString();
                        return `
                        <div class="details-container">
                        <h5>${task.name}</h5>
                        <p>Task started on: ${task._start.getDate()}</p>
                        <p>Expected to finish by ${task._start.getDate()}</p>
                        <p>${task.progress}% completed!</p>
                      </div>
                    `;
`

**Comment by HelbertCampos** [comment]
Use `popup` instead of `custom_popup_html`

**Comment by jurerejc** [comment]
Can you provide me an example, as I only get cusomt_popup_html examples? Also, why custom_popup_html this not working, if you have maybe this knowledge?

**Comment by safwansamsudeen** [comment]
Hi,

Sorry, this was changed back in April as it made more sense to have it all within one `popup` field. We'll update the examples soon.

**Comment by safwansamsudeen** [comment]
@jurerejc instead of `custom_popup_html`, just write `popup` and do your thing.

**Comment by rolliracker** [comment]
If I use `popup`, I dont get a popup at all (version 1.0.3). With `custom_popup_html` I have the same problem as the OP. Is there currently any way to get a custom popup?

**Comment by safwansamsudeen** [comment]
@rolliracker [The official website](https://frappe.io/gantt) uses popup and it works. Can you check your configuration?
