### ISSUE TITLE
Fixed Headerbar

### ISSUE THREAD

**Issue by tobehn** [frappe/gantt#467]
In order to be able to view all tasks and be able to get the set time period directly it would be great to have a fixed header. 

Basically like this:
- only the bars area should be vertically scrollable
- header and bars area should be horizontally scrollable

**Comment by safwansamsudeen** [comment]
Already exists - please uncomment the following lines in `index.html` to test it:

```
// Uncomment to test fixed header
// tasks = [
//     ...tasks,
//     ...Array.from({ length: tasks.length * 3 }, (_, i) => ({
//         ...tasks[i % 3],
//         id: i,
//     })),
// ];
```

**Comment by tobehn** [comment]
Is this possible in an ERPNext Installation?

**Comment by safwansamsudeen** [comment]
I don't think v0.8 has been implemented in ERPNext yet - I'll ask the team and get back to you.
