### ISSUE TITLE
use jalali date

### ISSUE THREAD

**Issue by webineh** [frappe/gantt#47]
hello  thank  you  for amazing gantt chart, i need change  date  type  to jalali with  jalali-moment 

how  i can integrate it with this 

https://github.com/jalaali/moment-jalaali

**Comment by netchampfaris** [comment]
@vahidalvandi Hi, I have recently removed the `moment.js` dependency. We will have to implement for jalaali using native `Date` API.

**Comment by Anurag810** [comment]
@netchampfaris is it implemented?

**Comment by RZsam** [comment]
@netchampfaris @Anurag810 
I couldn't find any other clue about Jalali calendar support
is it implemented?

**Comment by mehdinourollah** [comment]
Why this issue has been closed ?!
I can't find any Jalali Calendar support in this project

**Comment by yiiman-dev** [comment]
i am creating jalali version on this repository:
https://github.com/yiiman-dev/gantt
