### ISSUE TITLE
How to integrate in vue3?

### ISSUE THREAD

**Issue by Charlokkk** [frappe/gantt#472]
Thanks for providing such an excellent Gantt chart component, it is very useful to me, but when I integrated it in the vue3 project, the style did not take effect.  my project:

package.json
```
{
  "name": "gantt-demo",
  "version": "0.0.0",
  "private": true,
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview",
    "lint": "eslint . --fix"
  },
  "dependencies": {
    "frappe-gantt": "^0.9.0",
    "vue": "^3.5.13"
  },
  "devDependencies": {
    "@eslint/js": "^9.14.0",
    "@types/frappe-gantt": "^0.6.4",
    "@vitejs/plugin-vue": "^5.2.1",
    "eslint": "^9.14.0",
    "eslint-plugin-vue": "^9.30.0",
    "vite": "^6.0.1",
    "vite-plugin-vue-devtools": "^7.6.5"
  }
}
```

App.vue

```
<script setup>
import Gantt from "frappe-gantt";
import {onMounted, ref} from "vue";

const ganttRef = ref();
const gantt = ref(null);

const tasks = [
  {
    id: 'Task 1',
    name: 'Redesign website',
    start: '2016-12-28',
    end: '2016-12-31',
    progress: 20,
    dependencies: 'Task 2, Task 3',
    custom_class: 'bar-milestone' // optional
  }
];

const options = {
  header_height: 50,
  column_width: 30,
  step: 24,
  view_modes: ['Quarter Day', 'Half Day', 'Day', 'Week', 'Month'],
  bar_height: 20,
  bar_corner_radius: 3,
  arrow_curve: 5,
  padding: 18,
  view_mode: 'Day',
  date_format: 'YYYY-MM-DD',
  language: 'en', // or 'es', 'it', 'ru', 'ptBr', 'fr', 'tr', 'zh', 'de', 'hu'
  popup: null,
}

function initGantt() {
  gantt.value = new Gantt(ganttRef.value, tasks, options);
}

onMounted(() => {
  initGantt();
});


</script>

<template>
  <div>
    <div ref="ganttRef" class="gantt"/>
  </div>
</template>

<style scoped>

.gantt {
  width: 100%;
}
</style>
```

![1732962911034](https://github.com/user-attachments/assets/0bf7e27f-42bc-4156-a5fc-3a2831691a60)

Is there any problem with the above configuration and usage? How can I make the style take effect? ​​Or can you provide an integrated demo based on vue and vite? Thank you very much!

**Comment by xdewx** [comment]
> [@xdewx](https://github.com/xdewx) I don't understand - what are you struggling with?

As you can see at [https://github.com/frappe/gantt/issues/472#issue-2706759970](https://github.com/frappe/gantt/issues/472#issue-2706759970), though `import Gantt from "frappe-gantt"`, which `import './styles/frapper-gantt.css'`, the style is still not work.  And we can't solve the problem by `import 'frappe-gantt/dist/frapper-gantt.css'` for there is no releated export in `package.json`. Finally, we have to copy the css file manully.
