### ISSUE TITLE
Bug arrow - doesn't see it

### ISSUE THREAD

**Issue by LucasGreard** [frappe/gantt#479]
Hi ! 
I think i don't understand how arrow work.
I have this : I don't see arrow for dependencies

let tasks = [
                {
                    start: daysSince(-5),
                    end: daysSince(2),
                    name: 'Redesign website',
                    id: 'Task 0',
                    progress: random(),
                },
                {
                    start: daysSince(3),
                    duration: '6d',
                    name: 'Write new content',
                    id: 'Task 1',
                    progress: random(),
                    important: true,
                    dependencies: 'Task 0',
                },
                {
                    start: daysSince(4),
                    duration: '2d',
                    name: 'Apply new styles',
                    id: 'Task 2',
                    progress: random(),
                },
                {
                    start: daysSince(-4),
                    end: daysSince(0),
                    name: 'Review',
                    id: 'Task 3',
                    progress: random(),
                },
            ];

            AND 

const mutablity = new Gantt('#mutability', tasks, {
                header_height: 50,
                column_width: 30,
                step: 24,
                // view_modes: ['Quarter Day', 'Half Day', 'Day', 'Week', 'Month'],
                bar_height: 20,
                bar_corner_radius: 3,
                arrow_curve: 20,
                // padding: 18,
                // view_mode: 'Day',
                // date_format: 'YYYY-MM-DD',
                // language: 'fr', // or 'es', 'it', 'ru', 'ptBr', 'fr', 'tr', 'zh', 'de', 'hu'
                // popup: null,
            });

![image](https://github.com/user-attachments/assets/e4ffae1b-2afa-4960-912e-a90172db4d73)

**Comment by safwansamsudeen** [comment]
That is the correct usage, and you _should_ be getting the arrow.

Could you retry with the latest version (`git pull` from this repo)? Perhaps this was an old bug.

Here is the code I'm trying:
```js
let tasks = [
    {
        start: daysSince(-2),
        end: daysSince(2),
        name: 'Redesign website',
        id: 'Task 0',
        progress: random(),
    },
    {
        start: daysSince(3),
        duration: '6d',
        name: 'Write new content',
        id: 'Task 1',
        progress: random(),
        important: true,
        dependencies: 'Task 0',
    },
    {
        start: daysSince(4),
        duration: '2d',
        name: 'Apply new styles',
        id: 'Task 2',
        progress: random(),
    },
    {
        start: daysSince(-4),
        end: daysSince(0),
        name: 'Review',
        id: 'Task 3',
        progress: random(),
    },
];
const mutability = new Gantt('#mutability', tasks);
```

**Comment by safwansamsudeen** [comment]
Closing as no longer reproducible, and more general arrow bugs were fixed recently.
