### ISSUE TITLE
[Feature Request] Add configurable tick intervals for each view mode

### ISSUE THREAD

**Issue by KebabRonin** [frappe/gantt#480]
Adding the possibility to fix the interval of thick ticks in a view mode would make the gantt more customisable. For example, instead of these default ticks:

![image](https://github.com/user-attachments/assets/15f7a309-470f-491c-9aa8-f54bdd276ad3)
Using these ones:

![image](https://github.com/user-attachments/assets/d5b0eb8c-848c-45bd-a675-a6a6b9141eba)

The argument could look something like this, receiving a function which decides what day should have a thick tick:
```
var gantt = new Gantt(div, tasks, {
custom_view_modes: [
  {
    name: 'Day',
    thick_tick: function(date) {return date.getDay() == 4;} // Thick ticks every Friday
  }
]});
```
Another possible feature (although it might steer more towards a calendar rather than a gantt diagram) if this is done is adding support for custom rendering for some date intervals, such as weekends:
![image](https://github.com/user-attachments/assets/87f0a2e5-3c08-4842-bb9e-097865221c2d)
This could go into effect when there are consecutive thick ticks, or by another parameter.

**Comment by safwansamsudeen** [comment]
Already exists - the `thick_line` option in custom view modes (which have changed quite a bit - they're now called `view_modes`. Check `src/defaults.js` for more info.

View mode:
```js
{
    name: 'Day',
    padding: '14d',
    format_string: 'YYYY-MM-DD',
    step: '1d',
    lower_text: (d, ld, lang) =>
        !ld || d.getDate() !== ld.getDate()
            ? date_utils.format(d, 'D', lang)
            : '',
    upper_text: (d, ld, lang) =>
        !ld || d.getMonth() !== ld.getMonth()
            ? date_utils.format(d, 'MMMM', lang)
            : '',
    thick_line: (d) => d.getDate() === 1, // NOTE
},
```
Here's the rendering:
<img width="536" alt="image" src="https://github.com/user-attachments/assets/5a5f2d05-74ee-404e-abeb-ae3b88a1befe" />

I'm closing for now - if I misunderstood, will reopen.
