### ISSUE TITLE
If Today is outside the Schedule, the entire chart breaks.

### ISSUE THREAD

**Issue by jsic-sonapro** [frappe/gantt#481]
When the current Date (as in Today) is outside of the schedule, the entire chart can not be drawn, due to the following error:
![{FDEFFC6C-D756-4923-AA19-4705CCE44654}](https://github.com/user-attachments/assets/fe6e99ca-3089-4169-8f94-d97a139c6195)
I don't know if this behaviour is intended but it certainly doesn't feel that way, since I can easily imagine instances where someone wants to take a look at old or future schedules.

The error gets thrown due to the following null return at line 920:
```
get_closest_date() {
  let now = new Date();
  if (now < this.gantt_start || now > this.gantt_end) return null;
  //...
}
```
then 
```
highlightNow() {
  const [_, el] = this.get_closest_date();
  //...
}
```
recieves this null and promptly breaks, because the assignment can't handle null.

I managed to fix it by essentially just null-checking in Line 639 and Line 914:
```
highlightNow() {
  if (this.get_closest_date() == null) return;
  const [_, el] = this.get_closest_date();
  //...
}
```
```
scroll_today() {
  let [today, _] = this.get_closest_date() ?? [];
  this.set_scroll_position(today);
}
```
but that seems more like a bandaid fix than an actual educated one. If this is fine however, i'd gladly submit a PR.

**Comment by safwansamsudeen** [comment]
Thanks for calling this out! That was a _slight_ bandaid fix - it works, but it isn't enough as other bugs crop up (in the `scroll_today`, for example. We've fixed this.

(Just to be clear - this is the beta version. You didn't get this from the CDN, did you?)

**Comment by safwansamsudeen** [comment]
What version are you on?

**Comment by jsic-sonapro** [comment]
uuh the latest version at that point, the package.json says 0.9.0?

**Comment by safwansamsudeen** [comment]
Ah - we're yet to push the major release yet. Expect sometime this week!
