### ISSUE TITLE
Classic left side task list?

### ISSUE THREAD

**Issue by poVoq** [frappe/gantt#5]
Doesn't fit so well to the layout of ERPnext, but a classic view with a list of tasks to the left instead of having the task names ion top of the schedule would be nice as an option.

**Comment by netchampfaris** [comment]
@poVoq 
I started with that layout (left side task list), but that didn't go well.
So, maybe in the future, we could have multiple 'views', not as of now.

**Comment by manishbafna** [comment]
@netchampfaris is it possible to share the classic left side task list layout you have worked? 
I am thinking we can have another config where it can disable / enable such view.

**Comment by aohanhongzhi** [comment]
pls support the feature
