### ISSUE TITLE
Labels on first column

### ISSUE THREAD

**Issue by camux** [frappe/gantt#50]
Hi, It would be good, have a labels row as option on first column, we really need this feature

https://imgur.com/a/CSw4c

I can to work around this, and send PR.

**Comment by netchampfaris** [comment]
Nice feature to have. Contributions welcome.

**Comment by Anurag810** [comment]
@camux open the PR?

**Comment by sumancbd** [comment]
Hi, is this feature implemented? How do I do this? Any example pls?

**Comment by xsudiptaster** [comment]
examples will be helpful here

**Comment by safwansamsudeen** [comment]
Closing as this does not seem that useful - you can just have a separate first column with the labels.
