### ISSUE TITLE
Move tasks between arrows

### ISSUE THREAD

**Issue by camux** [frappe/gantt#51]
Sometimes we need that a task, pass to another arrow, so a task should be able move to another arrow

**Comment by netchampfaris** [comment]
What do you mean pass task to another arrow. Do you have an example scenario?

**Comment by Anurag810** [comment]
Please be more descriptive while explaining the issue and please follow the contribution guidelines while raising the issues
![Screenshot 2019-04-29 at 11 53 59 AM](https://user-images.githubusercontent.com/32095923/56880293-bb736600-6a79-11e9-8cac-e5afc05265bf.png)
