### ISSUE TITLE
Change mode view ... always in days in popup ?

### ISSUE THREAD

**Issue by jgorene** [frappe/gantt#54]
Hello,

First, I just begin to discover your effective and very user-friendly library  :+1: 

Just a little feedback about the feature "change view mode" : the durations in the popup are always displayed in days regardless of the mode chosen...
This may sound a bit wrong for the user and it's really damaging for your great job...

Temporarily, I just changed that in the configuration file passing a variable for this action ... 

- line 1364 `var line_1 = 'Duration:' + self.duration + 'days';`
- by `var line_1 = 'Duration:' + Math.round(self.duration*100)/100  + '  ' + gt.config.view_mode;`

I also rounded the duration to be there;)
Probably not ideal but it works well like that for now... what do you think about this?

Thanks very much again for your work often there are still small developments to fix

**Comment by joolsr** [comment]
@netchampfaris Hi Faris. Gantt charts have been broken in v10 Master for a few weeks now with the change view mode issue exactly as above. A few of us have reported on the forums / seen this issue independently 9I think there is a Issue in ERPNext Github too). I appreciate you are working on a new layout for Develop Gantt charts as I've tested it, but in Master it's broken ;-( , I hope you can fix ;-)

**Comment by netchampfaris** [comment]
@jgorene 
> Just a little feedback about the feature "change view mode" : the durations in the popup are always displayed in days regardless of the mode chosen...

This was intentional. The information in the popup is not tied to the view, you can put anything you want. It just shows the duration in days by default.

**Comment by netchampfaris** [comment]
@joolsr 
I think the issue described by @jgorene is related to the popup view.

It would be helpful if you could link to the Gantt issue in v10 you are talking about, so that I can get some context.

**Comment by joolsr** [comment]
its exactly the same as this one that you are aware of https://github.com/frappe/erpnext/issues/12316#issuecomment-363490402

**Comment by joolsr** [comment]
I can provide more details if you need them eg a video

**Comment by jgorene** [comment]
@netchampfaris, 
I understand that and yes indeed, it's an option that must be taken.
But your tool being highly configurable anyway, it's not a problem !

However, I will have other questions soon because your tool is great in features and visually successful to be very effective every day (imho ;)
Ok, thanks again

**Comment by jgorene** [comment]
@joolsr Hello,
For me @netchampfaris's answer is clear and corresponds to my waiting.
I close this thread and maybe it's better opening a new one with your own request which is apparently a little different, it seems anyway...
Thanks ;)
