### ISSUE TITLE
Is it possible to edit the Gantt chart from within the custom html popup?

### ISSUE THREAD

**Issue by QuantumRich** [frappe/gantt#55]
Let's say I have just shifted one of the tasks or pressed a button within the custom_html_popup, and wanted to either change the view_mode (to Months) or log out the new dates that I can then change my data with.

Is there an example?

**Comment by netchampfaris** [comment]
You have `change_view_mode` method on the Gantt instance.

**Comment by QuantumRich** [comment]
Is it possible to call the function within the custom_html_popup?

**Comment by netchampfaris** [comment]
You can certainly do it using delegated events. Just append some buttons in the `custom_html_popup` and set the click handler on the popup element itself.
