### ISSUE TITLE
Hover instead of click for custom_html_popup?

### ISSUE THREAD

**Issue by QuantumRich** [frappe/gantt#59]
Is it possible to set it so the popup shows up during a hover instead of a click event?

Is there somewhere in the code I can do this?

**Comment by loyin** [comment]
the lasted version can't

**Comment by netchampfaris** [comment]
It is currently activated on `focus` and `click`, we can do it on `hover` but it should be configurable. Contributions welcome.

**Comment by loyin** [comment]
think you.I used in vuejs2.0.
