### ISSUE TITLE
Scroll update method does not work?

### ISSUE THREAD

**Issue by fsp22** [frappe/gantt#62]
In my test, the scroll position of the svg parent element is always 0. Changing reference from $svg to $container fix the issue.

https://github.com/frappe/gantt/blob/5a03973e06e6a4236d88ef58ffbf792d8103cd9c/src/index.js#L545

**Comment by netchampfaris** [comment]
It works fine on my machine with $svg. Need more details than this to reproduce.

**Comment by Anurag810** [comment]
Please be more descriptive while explaining the issue.
