### ISSUE TITLE
Expected ':' 

### ISSUE THREAD

**Issue by HugRios** [frappe/gantt#80]
I tried to embed the library in my project.
    <script type="text/javascript" src="../assets/libraries/gantt-master/dist/frappe-gantt.js"></script>

but i get the next error:
 Expected ':'
File: frappe-gantt.min.js, Line: 1, Column: 167

could someone help me with this issue?

**Comment by Adioud** [comment]
Hello,

To have more information about this error you shoud use the non-minified version.

I just noticed the same problem: it seems that a lot of syntaxe is not compatible with IE11...
)-;

**Comment by safwansamsudeen** [comment]
I think we don't really support IE at this point, but will revert if we do.
