### ISSUE TITLE
How to make chart without Tasks

### ISSUE THREAD

**Issue by walt1992** [frappe/gantt#84]
Clients may use this chart first with no tasks. 
So, I want make Default Ganttchart without Tasks. How Can I do resolve this issue??

**Comment by dkrusenstrahle** [comment]
I have the same issue,  any fixes?

**Comment by enricribas** [comment]
I think this project is abandoned. :(

**Comment by dkrusenstrahle** [comment]
That is unfortunate. It´s the only good Gantt chart I can find for Angular :(

**Comment by enricribas** [comment]
Agreed, I use it with Vue but same. Only decent one that isn't very expensive. (read: free) :)

**Comment by MinsikPark** [comment]
Actually I fixed this problem with Default data. 
When loading GanttChart, I set some sample data in javascript and make ganttChart. 
After then just hide created Bars using css options... 
this is only solution I found.

**Comment by safwansamsudeen** [comment]
This was fixed.
