### ISSUE TITLE
Unable to import from dist/frappe-gantt.js

### ISSUE THREAD

**Issue by yjchen** [frappe/gantt#85]
I can import Gantt from frappe-gantt/src/index.js, but not frappe-gantt/dist/frappe-gantt.js. The **export** is missing in **dist/frappe-gantt.js**. Is it expected behavior ? I usually import from **dist/** from other javascript library, not directly from **src/**

**Comment by jamieday** [comment]
Yes, this behavior is expected.

The distribution file is bundled so it's meant to be put before your JavaScript code in a browser (for example, in the `<head>` tag) and then you can access the Gantt object globally.

For example:
```HTML
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Simple Gantt</title>
	<link rel="stylesheet" href="dist/frappe-gantt.css" />
	<script src="dist/frappe-gantt.js"></script>
</head>
<body>
	<div class="gantt-target"></div>
	<script src="your_javascript_here.js"></script>
</body>
</html>
```

**Comment by netchampfaris** [comment]
Maybe we should add a ES6 bundle too
