### ISSUE TITLE
Feauture Request: Year View

### ISSUE THREAD

**Issue by Mashiane** [frappe/gantt#87]
Can you kindly add a year view. This could be useful where a project spans many years.

Thanks

**Comment by ThomasKuhlmann** [comment]
+1
It would be good if we could also have a "show all" view so that you can see all tasks at the same time, no matter how long the project is.

**Comment by airflyer13** [comment]
+1 to both ideas, would be extremely useful

**Comment by Anurag810** [comment]
The year view is available now #96
