### ISSUE TITLE
Add "Project" field for grouping tasks

### ISSUE THREAD

**Issue by Dbonejones** [frappe/gantt#9]
Task groups could be implemented by adding a top level "Project" field to the gantt chart. The project would be the top level of a group of tasks, and tasks should be "dependent" on the project since tasks need to be within the project timeline. The gantt chart in ERPNext could populate this field from the projects module as an added bonus.

To make the chart visually easy to read:

- Slightly separate projects (a line in between) on the timeline
- ability to collapse a project to save space when viewing many projects simultaneously
- ability to collapse a task if it has dependents
- show the project name in the popover of each task
- show an error if you modify the project start or end date and it cuts off a task
- show an error if you add a task to a project that falls outside the project dates
- Moving the project on the timeline moves all the associated tasks

Icing on the cake would be unique Project and Task colours:

- Assign a project a colour and all associated tasks are assigned that colour
- Assign a task a colour and it overrides the project colour for itself only
- completed percentage should be grey
- Use the purple colour as a default project and task colour if nothing is selected

**Comment by netchampfaris** [comment]
@Dbonejones Grouping Projects by Task is certainly a good feature. Will work on it when I have time.

For color coding Tasks, you can add CSS class to each task (https://github.com/frappe/gantt/pull/14)

**Comment by Anurag810** [comment]
Issue fixed by #93
