### ISSUE TITLE
Selection issues

### ISSUE THREAD

**Issue by dynjo** [frappe/gantt#92]
In the current master there seems to be many selection related issues compared with the version on [https://frappe.io/gantt](https://frappe.io/gantt). eg.

- Clicking the text makes the bar disappear
- Resizing and dragging selects the text and header area

Issues in both Safari and Chrome.

![2018-07-06 at 7 53 pm](https://user-images.githubusercontent.com/184405/42380024-b9ab23c4-8156-11e8-8d77-849e4b54b329.gif)

**Comment by jwpully** [comment]
I am experiencing the same issue.  Is there any update on this?

**Comment by Hkly** [comment]
Adding `pointer-events: none;` to the `.bar-label` fixed the bar disappearing/jumping for me. Also happens to prevent the text from being selected as well.

**Comment by safwansamsudeen** [comment]
Fixed in #382.
