### ISSUE TITLE
React build failed to minify file

### ISSUE THREAD

**Issue by gravitano** [frappe/gantt#94]
Hey, 

I use https://github.com/hustcc/gantt-for-react version 0.2.0 that is react wrapper of this package. But, when i build, i got error that react coudn't compile file `svg_utils.js:9 `. 

Here's the full error messages.
```
yarn run v1.7.0
$ cross-env REACT_APP_BUILD_ENV=production react-scripts build
Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file: 

 	./node_modules/frappe-gantt/src/svg_utils.js:9 

Read more here: http://bit.ly/2tRViJ9

error Command failed with exit code 1.
```

**Comment by hustcc** [comment]
issue here: https://github.com/hustcc/gantt-for-react/issues/9

**Comment by chathuraa** [comment]
I'm having the same issue.

**Comment by ywlearn** [comment]
Anyone got a solution? It confused me whole day.

**Comment by hustcc** [comment]
issue of frappe-gantt.
